import { StyleSheet } from 'react-native';

import { fonts, typography } from '@/src/theme';

export const relicStyles = StyleSheet.create({
  stage: {
    position: 'relative',
    zIndex: 2,
    height: 365,
    marginTop: -58,
    marginHorizontal: -10,
    marginBottom: -3,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  stagePressed: { transform: [{ scale: .994 }] },
  sceneBackdrop: {
    position: 'absolute',
    zIndex: 0,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  arch: {
    position: 'absolute',
    zIndex: 2,
    top: -2,
    width: 348,
    height: 348,
    opacity: .78,
  },
  haloCanvas: {
    position: 'absolute',
    zIndex: 1,
    width: '100%',
    height: 279,
    top: 0,
    alignItems: 'center',
    overflow: 'hidden',
  },
  vesselCanvas: {
    position: 'absolute',
    zIndex: 4,
    width: '100%',
    height: 270,
    top: 5,
    alignItems: 'center',
    overflow: 'visible',
  },
  coldAura: {
    position: 'absolute',
    width: 278,
    height: 254,
    top: 10,
    borderRadius: 139,
  },
  glassHalo: {
    position: 'absolute',
    width: 190,
    height: 238,
    top: 22,
    borderRadius: 95,
  },
  amberAura: {
    position: 'absolute',
    width: 126,
    height: 126,
    bottom: 24,
    borderRadius: 63,
    backgroundColor: 'rgba(226,139,55,.14)',
    boxShadow: '0 0 52px rgba(224,137,55,.28)',
  },
  wireLeft: {
    position: 'absolute',
    width: 188,
    height: 1,
    left: -18,
    top: 151,
    backgroundColor: 'rgba(175,105,62,.2)',
    transform: [{ rotate: '-12deg' }],
  },
  wireRight: {
    position: 'absolute',
    width: 188,
    height: 1,
    right: -18,
    top: 151,
    backgroundColor: 'rgba(175,105,62,.2)',
    transform: [{ rotate: '12deg' }],
  },
  haloFade: {
    position: 'absolute',
    zIndex: 10,
    right: 0,
    bottom: 0,
    left: 0,
    height: 22,
  },
  image: {
    position: 'absolute',
    zIndex: 3,
    width: 220,
    height: 330,
    top: -44,
  },
  liquidMotion: {
    position: 'absolute',
    zIndex: 4,
    width: 122,
    height: 110,
    bottom: 28,
    borderRadius: 61,
  },
  liquidGlow: { width: '100%', height: '100%', borderRadius: 61 },
  coreGlow: {
    position: 'absolute',
    zIndex: 5,
    width: 39,
    height: 39,
    bottom: 42,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coreSpark: {
    width: 14,
    height: 14,
    borderRadius: 8,
    backgroundColor: 'rgba(255,180,75,.96)',
    boxShadow: '0 0 12px rgba(255,211,105,.78)',
  },
  bubble: {
    position: 'absolute',
    zIndex: 6,
    borderWidth: 1,
    borderColor: 'rgba(169,236,238,.62)',
    backgroundColor: 'rgba(45,166,181,.08)',
    boxShadow: '0 0 8px rgba(64,202,213,.22)',
  },
  bubbleLarge: { width: 10, height: 10, right: 113, bottom: 95, borderRadius: 5 },
  bubbleSmall: { width: 6, height: 6, left: 119, bottom: 122, borderRadius: 3 },
  bubbleHighlight: {
    position: 'absolute',
    width: '34%',
    height: '34%',
    left: '16%',
    top: '13%',
    borderRadius: 99,
    backgroundColor: 'rgba(244,255,255,.86)',
  },
  contactLightLayer: {
    position: 'absolute',
    zIndex: 5,
    top: 251,
    width: 100,
    height: 23,
    alignItems: 'center',
    overflow: 'hidden',
  },
  contactBloom: {
    position: 'absolute',
    top: 0,
    width: 80,
    height: 20,
    borderRadius: 40,
  },
  contactCore: {
    position: 'absolute',
    top: 17,
    width: 72,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(226,253,255,.96)',
    boxShadow: '0 0 12px rgba(50,224,238,.84)',
  },
  contactCopperReflection: {
    position: 'absolute',
    zIndex: 7,
    top: 272,
    width: 86,
    height: 1,
    backgroundColor: 'rgba(242,166,94,.76)',
    boxShadow: '0 0 5px rgba(225,132,68,.38)',
  },
  reveal: {
    position: 'absolute',
    zIndex: 12,
    top: 8,
    minWidth: 148,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 15,
    alignItems: 'center',
    backgroundColor: 'rgba(5,10,13,.92)',
    borderWidth: 1,
    borderColor: '#7C5A32',
    boxShadow: '0 0 22px rgba(199,131,60,.2)',
  },
  revealEyebrow: { ...typography.eyebrow, color: '#E8FF3D', fontSize: 8, lineHeight: 10, letterSpacing: .7 },
  revealName: { marginTop: 2, color: '#F4F1EA', fontFamily: fonts.display, fontSize: 16, lineHeight: 18 },
});
