import { StyleSheet } from 'react-native';

import { fonts, typography } from '@/src/theme';

export const COMPACT_RELIC_SCALE = .92;

export const relicStyles = StyleSheet.create({
  stage: {
    position: 'relative',
    zIndex: 2,
    height: 365,
    marginTop: -58,
    marginHorizontal: -10,
    marginBottom: -3,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    outlineWidth: 0,
    outlineStyle: 'solid',
    outlineColor: 'transparent',
  },
  stageCompact: {
    height: 290,
    marginTop: -48,
    marginHorizontal: -34,
    marginBottom: -12,
    transform: [{ scale: COMPACT_RELIC_SCALE }],
  },
  sceneBackdrop: {
    position: 'absolute',
    zIndex: 0,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  mutationBackdrop: {
    position: 'absolute',
    zIndex: 1,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#000000',
  },
  arch: {
    position: 'absolute',
    zIndex: 2,
    top: -2,
    width: 348,
    height: 348,
    opacity: .78,
  },
  haloCanvas: {
    position: 'absolute',
    zIndex: 1,
    width: '100%',
    height: 279,
    top: 0,
    alignItems: 'center',
    overflow: 'hidden',
  },
  ambientEnergy: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
  },
  coldAura: {
    position: 'absolute',
    width: 278,
    height: 254,
    top: 10,
    borderRadius: 139,
  },
  glassHalo: {
    position: 'absolute',
    width: 190,
    height: 238,
    top: 22,
    borderRadius: 95,
  },
  amberAura: {
    position: 'absolute',
    width: 126,
    height: 126,
    bottom: 24,
    borderRadius: 63,
    backgroundColor: 'rgba(226,139,55,.14)',
    boxShadow: '0 0 52px rgba(224,137,55,.28)',
  },
  wireLeft: {
    position: 'absolute',
    width: 188,
    height: 1,
    left: -18,
    top: 151,
    backgroundColor: 'rgba(175,105,62,.2)',
    transform: [{ rotate: '-12deg' }],
  },
  wireRight: {
    position: 'absolute',
    width: 188,
    height: 1,
    right: -18,
    top: 151,
    backgroundColor: 'rgba(175,105,62,.2)',
    transform: [{ rotate: '12deg' }],
  },
  haloFade: {
    position: 'absolute',
    zIndex: 10,
    right: 0,
    bottom: 0,
    left: 0,
    height: 22,
  },
  resonanceRing: {
    position: 'absolute',
    zIndex: 4,
    top: 102,
    width: 180,
    height: 180,
  },
  vesselCanvas: {
    position: 'absolute',
    zIndex: 5,
    width: '100%',
    height: 270,
    top: 5,
    alignItems: 'center',
    overflow: 'visible',
  },
  vesselMotionLayer: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  signatureField: {
    position: 'absolute',
    zIndex: 4,
    top: 74,
    width: 172,
    height: 172,
    borderRadius: 86,
    backgroundColor: 'rgba(48,215,226,.26)',
    boxShadow: '0 0 38px rgba(48,215,226,.34), 0 0 72px rgba(164,73,255,.2)',
  },
  signaturePulseRing: {
    position: 'absolute',
    zIndex: 7,
    top: 96,
    width: 126,
    height: 126,
    borderRadius: 63,
    borderWidth: 1,
    borderColor: 'rgba(217,250,255,.82)',
    boxShadow: '0 0 20px rgba(48,215,226,.7), inset 0 0 16px rgba(164,73,255,.26)',
  },
  signatureOrbit: {
    position: 'absolute',
    zIndex: 7,
    top: 82,
    width: 158,
    height: 158,
    borderRadius: 79,
    borderWidth: 1,
    borderColor: 'rgba(73,226,237,.42)',
    borderStyle: 'dashed',
    boxShadow: '0 0 16px rgba(48,215,226,.22)',
  },
  signatureOrbitNode: {
    position: 'absolute',
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#9AF6FF',
    boxShadow: '0 0 12px rgba(109,239,248,.92)',
  },
  signatureOrbitNodePrimary: {
    top: -4,
    left: 75,
  },
  signatureOrbitNodeSecondary: {
    right: 10,
    bottom: 16,
    width: 4,
    height: 4,
    backgroundColor: '#C58BFF',
    boxShadow: '0 0 10px rgba(197,139,255,.9)',
  },
  image: {
    position: 'absolute',
    zIndex: 1,
    width: 220,
    height: 330,
    top: -44,
  },
  labVesselTransition: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
  },
  mutationRevealClip: {
    position: 'absolute',
    zIndex: 6,
    alignItems: 'center',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  mutationVesselInner: {
    position: 'relative',
    flexShrink: 0,
  },
  mutationVesselImage: {
    position: 'absolute',
    zIndex: 1,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  mutationVesselLiquid: {
    position: 'absolute',
    zIndex: 2,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  mutationVesselRoots: {
    position: 'absolute',
    zIndex: 3,
  },
  mutationVesselEffects: {
    position: 'absolute',
    zIndex: 6,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  mutationEnergyLayer: {
    position: 'absolute',
    zIndex: 8,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  mutationHeartAura: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: 'rgba(242,158,64,.28)',
    boxShadow: '0 0 30px rgba(255,189,84,.7), 0 0 44px rgba(49,215,226,.22)',
  },
  mutationHeart: {
    position: 'absolute',
    zIndex: 3,
  },
  mutationLocalFlash: {
    position: 'absolute',
    zIndex: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(229,253,255,.82)',
    boxShadow: '0 0 28px rgba(49,215,226,.92), 0 0 42px rgba(242,158,64,.68)',
  },
  mutationImplosionWave: {
    position: 'absolute',
    zIndex: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(118,239,245,.86)',
    boxShadow: '0 0 12px rgba(49,215,226,.52)',
  },
  labContainerImage: {
    position: 'absolute',
    zIndex: 1,
  },
  labLiquidLayer: {
    position: 'absolute',
    zIndex: 2,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  labRootsLayer: {
    position: 'absolute',
    zIndex: 3,
  },
  labMutationAura: {
    position: 'absolute',
    zIndex: 4,
    top: 78,
    width: 214,
    height: 214,
    borderRadius: 107,
    backgroundColor: 'rgba(219,139,64,.08)',
    boxShadow: '0 0 54px rgba(48,215,226,.24), 0 0 76px rgba(219,139,64,.16)',
  },
  labHeartAura: {
    position: 'absolute',
    zIndex: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(229,139,48,.22)',
    boxShadow: '0 0 22px rgba(240,151,52,.52)',
  },
  labHeart: {
    position: 'absolute',
    zIndex: 5,
  },
  labCoreWave: {
    position: 'absolute',
    zIndex: 6,
    width: 52,
    height: 32,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(246,169,79,.76)',
    boxShadow: '0 0 10px rgba(240,145,52,.3)',
  },
  labRefraction: {
    position: 'absolute',
    zIndex: 7,
    overflow: 'hidden',
    borderRadius: 999,
  },
  labGlassHighlights: {
    position: 'absolute',
    zIndex: 8,
  },
  supporterInternalArtwork: {
    position: 'absolute',
    zIndex: 7,
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  ampouleInternalArtwork: {
    top: -44,
    left: '50%',
    width: 220,
    height: 330,
    marginLeft: -110,
  },
  liquidMask: {
    position: 'absolute',
    zIndex: 2,
    top: 132,
    width: 124,
    height: 120,
    overflow: 'hidden',
    borderTopLeftRadius: 47,
    borderTopRightRadius: 47,
    borderBottomLeftRadius: 62,
    borderBottomRightRadius: 62,
  },
  liquidArtwork: {
    position: 'absolute',
    zIndex: 1,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  oldCoreVeil: {
    position: 'absolute',
    zIndex: 2,
    left: 23,
    bottom: -3,
    width: 78,
    height: 76,
    borderRadius: 39,
  },
  rootsLayer: {
    position: 'absolute',
    zIndex: 3,
    top: -34,
    right: 0,
    bottom: 34,
    left: 0,
  },
  heartAura: {
    position: 'absolute',
    zIndex: 4,
    left: 30,
    bottom: -6,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(235,139,48,.36)',
    boxShadow: '0 0 24px rgba(244,151,47,.56)',
  },
  heart: {
    position: 'absolute',
    zIndex: 5,
    left: 34,
    bottom: -2,
    width: 56,
    height: 56,
  },
  heartWave: {
    position: 'absolute',
    zIndex: 6,
    left: 38,
    bottom: 9,
    width: 48,
    height: 32,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(246,169,79,.84)',
    boxShadow: '0 0 10px rgba(240,145,52,.34)',
  },
  liquidRefraction: {
    position: 'absolute',
    zIndex: 7,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  liquidRefractionFill: { width: '100%', height: '100%' },
  glassHighlights: {
    position: 'absolute',
    zIndex: 8,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  bubble: {
    position: 'absolute',
    zIndex: 9,
    width: 7,
    height: 7,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(177,240,244,.68)',
    backgroundColor: 'rgba(68,180,194,.09)',
    boxShadow: '0 0 7px rgba(72,211,222,.24)',
  },
  idleBubble: { left: 75, bottom: 23 },
  idleBubbleTwo: { left: 43, bottom: 26, width: 5, height: 5 },
  idleBubbleThree: { left: 88, bottom: 20, width: 4, height: 4 },
  tapBubble: { left: 47, bottom: 25, width: 6, height: 6 },
  resonanceBubbleOne: { left: 54, bottom: 23, width: 6, height: 6 },
  resonanceBubbleTwo: { left: 66, bottom: 19, width: 8, height: 8 },
  resonanceBubbleThree: { left: 79, bottom: 24, width: 5, height: 5 },
  bubbleHighlight: {
    position: 'absolute',
    width: '34%',
    height: '34%',
    left: '16%',
    top: '13%',
    borderRadius: 99,
    backgroundColor: 'rgba(244,255,255,.86)',
  },
  contactLightLayer: {
    position: 'absolute',
    zIndex: 9,
    top: 264,
    height: 10,
    alignItems: 'center',
    overflow: 'hidden',
  },
  contactBloom: {
    position: 'absolute',
    top: 0,
    width: '100%',
    height: 9,
    borderRadius: 99,
  },
  mutationContactSurface: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
  },
  contactCore: {
    position: 'absolute',
    top: 3,
    height: 3,
    borderRadius: 99,
    backgroundColor: 'rgba(226,253,255,.96)',
    boxShadow: '0 0 9px rgba(50,224,238,.76)',
  },
  contactCopperReflection: {
    position: 'absolute',
    zIndex: 11,
    top: 272,
    width: 86,
    height: 1,
    backgroundColor: 'rgba(242,166,94,.76)',
    boxShadow: '0 0 5px rgba(225,132,68,.38)',
  },
  supporterPedestalSegment: {
    position: 'absolute',
    zIndex: 12,
    top: 272,
    width: 11,
    height: 2,
    borderRadius: 2,
    backgroundColor: 'rgba(249,182,86,.98)',
    borderTopWidth: .5,
    borderTopColor: 'rgba(158,244,248,.72)',
    boxShadow: '0 0 7px rgba(238,160,71,.62)',
  },
  reveal: {
    position: 'absolute',
    zIndex: 20,
    top: 8,
    minWidth: 148,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 15,
    alignItems: 'center',
    backgroundColor: 'rgba(5,10,13,.92)',
    borderWidth: 1,
    borderColor: '#7C5A32',
    boxShadow: '0 0 22px rgba(199,131,60,.2)',
  },
  labReveal: { right: 8 },
  revealEyebrow: { ...typography.eyebrow, color: '#E8FF3D', fontSize: 8, lineHeight: 10, letterSpacing: .7 },
  revealName: { marginTop: 2, color: '#F4F1EA', fontFamily: fonts.display, fontSize: 16, lineHeight: 18 },
});
