import { StyleSheet } from 'react-native';

import { colors, layout, radius, spacing } from '@/src/theme';

export const styles = StyleSheet.create({
  content: {
    width: '100%',
    maxWidth: layout.contentMaxWidth,
    alignSelf: 'center',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: layout.tabBarContentInset,
    gap: spacing.xl,
  },
  header: { gap: 8, paddingTop: 4 },
  eyebrow: { color: colors.volt, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 },
  title: { color: colors.text, fontSize: 34, lineHeight: 38, fontWeight: '900', letterSpacing: -1.2 },
  subtitle: { color: colors.textMuted, fontSize: 14, lineHeight: 20, maxWidth: 380 },
  errorBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, padding: 14, borderRadius: radius.md, backgroundColor: '#1A1012', borderWidth: 1, borderColor: '#4A2027' },
  errorText: { flex: 1, color: '#FF9AA2', fontSize: 12, lineHeight: 17 },
  retry: { color: colors.volt, fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  hero: { position: 'relative', overflow: 'hidden', borderRadius: 28, borderWidth: 1, backgroundColor: '#0A0F14', padding: 18, gap: 18 },
  heroAura: { position: 'absolute', width: 260, height: 260, borderRadius: 130, top: 80, alignSelf: 'center', opacity: 0.9 },
  identityRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, zIndex: 2 },
  identityLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  identityCopy: { flex: 1, minWidth: 0 },
  identityEyebrow: { color: colors.textMuted, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  factionName: { marginTop: 2, color: colors.text, fontSize: 20, fontWeight: '900', letterSpacing: -0.5 },
  factionMeta: { marginTop: 3, color: colors.textMuted, fontSize: 9, fontWeight: '700', letterSpacing: 0.5 },
  rankPill: { minWidth: 44, height: 36, paddingHorizontal: 12, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border },
  rankText: { color: colors.text, fontSize: 13, fontWeight: '900' },
  teamBadge: { alignItems: 'center', justifyContent: 'center', borderWidth: 1.2 },
  teamBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900', letterSpacing: 0.2 },
  teamBadgeTextLarge: { fontSize: 13 },
  signalRow: { zIndex: 2, minHeight: 34, borderRadius: 17, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#0D141A', borderWidth: 1, borderColor: colors.border },
  signalDot: { width: 7, height: 7, borderRadius: 4 },
  signalText: { color: colors.text, fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  signalRemaining: { flex: 1, color: colors.textMuted, fontSize: 9, textAlign: 'right' },
  relicStage: { zIndex: 2, minHeight: 270, alignItems: 'center', justifyContent: 'center', paddingTop: 8 },
  relicGlow: { position: 'absolute', width: 190, height: 190, borderRadius: 95, top: 20 },
  ring: { position: 'absolute', borderWidth: 1, borderRadius: 999 },
  ringOuter: { width: 210, height: 210, top: 10 },
  ringInner: { width: 150, height: 150, top: 40 },
  relicShell: { height: 180, width: 190, alignItems: 'center', justifyContent: 'flex-end' },
  cork: { width: 36, height: 17, borderTopLeftRadius: 7, borderTopRightRadius: 7, backgroundColor: '#332A21', borderWidth: 1, borderColor: '#5B4A39', zIndex: 3 },
  neck: { height: 28, marginTop: -2, backgroundColor: 'rgba(173,198,210,0.08)', borderLeftWidth: 1, borderRightWidth: 1, borderColor: 'rgba(188,214,227,0.28)' },
  vessel: { position: 'relative', overflow: 'hidden', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(173,198,210,0.045)', borderWidth: 1.2 },
  liquid: { position: 'absolute', bottom: 0, left: 0, right: 0, opacity: 0.88 },
  core: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, backgroundColor: 'rgba(7,10,14,0.72)' },
  coreInner: { width: 16, height: 16, borderRadius: 8, backgroundColor: colors.volt },
  glassShine: { position: 'absolute', width: 5, top: 12, bottom: 18, left: 14, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.17)' },
  relicCharm: { position: 'absolute', right: 29, top: 56, width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', borderWidth: 1, backgroundColor: '#080C10' },
  relicCharmText: { fontSize: 8, fontWeight: '900' },
  relicLabel: { marginTop: 14, alignItems: 'center', gap: 2 },
  formCode: { color: colors.textMuted, fontSize: 8, fontWeight: '900', letterSpacing: 1.5 },
  formName: { color: colors.text, fontSize: 22, fontWeight: '900', letterSpacing: -0.6 },
  formPhrase: { marginTop: 2, color: colors.textMuted, fontSize: 11, lineHeight: 16, textAlign: 'center', maxWidth: 280 },
  chargeBlock: { zIndex: 2, padding: 14, borderRadius: radius.md, backgroundColor: 'rgba(6,10,14,0.78)', borderWidth: 1, borderColor: colors.border, gap: 10 },
  chargeHeadline: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  chargeEyebrow: { color: colors.textMuted, fontSize: 8, fontWeight: '900', letterSpacing: 1.1 },
  chargeValue: { marginTop: 3, color: colors.text, fontSize: 16, fontWeight: '900' },
  chargePct: { fontSize: 21, fontWeight: '900' },
  track: { height: 7, borderRadius: 999, overflow: 'hidden', backgroundColor: colors.surfaceElevated },
  trackFill: { height: '100%', borderRadius: 999 },
  chargeHint: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  nextMutation: { zIndex: 2, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 12, borderRadius: radius.md, backgroundColor: '#0E141A', borderWidth: 1, borderColor: colors.border },
  nextMutationMark: { width: 40, height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0A0F14', borderWidth: 1, borderColor: colors.border },
  nextMutationCode: { color: colors.textMuted, fontSize: 12, fontWeight: '900' },
  nextMutationCopy: { flex: 1, minWidth: 0 },
  nextMutationEyebrow: { color: colors.textMuted, fontSize: 7, fontWeight: '900', letterSpacing: 1 },
  nextMutationTitle: { marginTop: 2, color: colors.text, fontSize: 14, fontWeight: '900' },
  nextMutationDetail: { marginTop: 2, color: colors.textMuted, fontSize: 9 },
  rewardPill: { alignItems: 'flex-end' },
  rewardValue: { color: colors.volt, fontSize: 13, fontWeight: '900' },
  rewardUnit: { color: colors.textMuted, fontSize: 7, fontWeight: '900', letterSpacing: 1 },
  visitorNotice: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, padding: 15, borderRadius: radius.lg, backgroundColor: '#0C1117', borderWidth: 1, borderColor: colors.border },
  visitorIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: '#131A22' },
  visitorIconText: { color: colors.volt, fontSize: 17 },
  visitorCopy: { flex: 1, gap: 4 },
  visitorTitle: { color: colors.text, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  visitorText: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  section: { gap: 13 },
  sectionHeading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  sectionEyebrow: { color: colors.textMuted, fontSize: 9, fontWeight: '900', letterSpacing: 1.3 },
  sectionTitle: { marginTop: 4, color: colors.text, fontSize: 20, lineHeight: 24, fontWeight: '900', letterSpacing: -0.5 },
  sectionMeta: { color: colors.textMuted, fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  rankingCard: { overflow: 'hidden', borderRadius: radius.lg, backgroundColor: '#0B1015', borderWidth: 1, borderColor: colors.border },
  rankRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#171F28' },
  rankRowFocused: { backgroundColor: '#10171E' },
  rankNumber: { width: 24, color: colors.textMuted, fontSize: 11, fontWeight: '900' },
  rankNumberLeader: { color: colors.volt },
  rankTeamCopy: { flex: 1, minWidth: 0 },
  rankTeamLine: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  rankTag: { color: colors.text, fontSize: 12, fontWeight: '900' },
  mePill: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 999, backgroundColor: '#202812' },
  mePillText: { color: colors.volt, fontSize: 6, fontWeight: '900', letterSpacing: 0.5 },
  rankDetail: { marginTop: 3, color: colors.textMuted, fontSize: 9 },
  speedBlock: { alignItems: 'flex-end', minWidth: 68 },
  speedValue: { color: colors.text, fontSize: 13, fontWeight: '900' },
  speedPositive: { color: colors.success },
  speedHint: { marginTop: 3, color: colors.textMuted, fontSize: 7, fontWeight: '800' },
  impactCard: { padding: 15, borderRadius: radius.lg, backgroundColor: '#0B1015', borderWidth: 1, borderColor: colors.border, gap: 14 },
  impactStats: { flexDirection: 'row', gap: 8 },
  impactStat: { flex: 1, minWidth: 0, padding: 11, borderRadius: radius.md, backgroundColor: '#10161D', borderWidth: 1, borderColor: '#1C2530' },
  impactStatLabel: { color: colors.textMuted, fontSize: 7, fontWeight: '900', letterSpacing: 0.8 },
  impactStatValue: { marginTop: 5, color: colors.text, fontSize: 16, fontWeight: '900' },
  positive: { color: colors.success },
  negative: { color: colors.danger },
  impactDivider: { height: 1, backgroundColor: colors.border },
  topLabel: { color: colors.textMuted, fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  contributorRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 9 },
  contributorRank: { width: 24, color: colors.textMuted, fontSize: 10, fontWeight: '900' },
  contributorAvatar: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceElevated },
  contributorInitials: { color: colors.text, fontSize: 8, fontWeight: '900' },
  contributorCopy: { flex: 1, minWidth: 0 },
  contributorName: { color: colors.text, fontSize: 11, fontWeight: '800' },
  contributorDetail: { marginTop: 2, color: colors.textMuted, fontSize: 8 },
  youBadge: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 999, backgroundColor: '#222A13' },
  youBadgeText: { color: colors.volt, fontSize: 7, fontWeight: '900' },
  inlineEmpty: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  archiveCard: { overflow: 'hidden', borderRadius: radius.lg, backgroundColor: '#0B1015', borderWidth: 1, borderColor: colors.border },
  archiveRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 13, borderBottomWidth: 1, borderBottomColor: '#171F28' },
  archiveMark: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#131A22', borderWidth: 1, borderColor: colors.border },
  archiveMarkOrigin: { backgroundColor: '#222A13', borderColor: '#3B4820' },
  archiveCode: { color: colors.textMuted, fontSize: 9, fontWeight: '900' },
  archiveCodeOrigin: { color: colors.volt },
  archiveCopy: { flex: 1, minWidth: 0 },
  archiveTitle: { color: colors.text, fontSize: 12, fontWeight: '900' },
  archiveDetail: { marginTop: 3, color: colors.textMuted, fontSize: 9 },
  archiveReward: { color: colors.volt, fontSize: 10, fontWeight: '900' },
  archiveEmpty: { padding: 16 },
  archiveEmptyText: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  formsRail: { gap: 10, paddingRight: spacing.md },
  formCard: { width: 126, minHeight: 146, padding: 13, borderRadius: radius.lg, backgroundColor: '#090D12', borderWidth: 1, borderColor: '#171E27' },
  formCardUnlocked: { backgroundColor: '#0D1318', borderColor: '#27313C' },
  formCardCurrent: { borderColor: '#59651E', backgroundColor: '#11170E' },
  formCardCode: { color: '#4E5863', fontSize: 20, fontWeight: '900' },
  formCardCodeUnlocked: { color: colors.volt },
  formCardName: { marginTop: 15, color: colors.text, fontSize: 15, fontWeight: '900' },
  formCardThreshold: { marginTop: 4, color: colors.textMuted, fontSize: 7, fontWeight: '800' },
  formState: { marginTop: 'auto', alignSelf: 'flex-start', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 999, backgroundColor: '#11161C' },
  formStateUnlocked: { backgroundColor: '#222A13' },
  formStateText: { color: '#59636E', fontSize: 6, fontWeight: '900', letterSpacing: 0.6 },
  formStateTextUnlocked: { color: colors.volt },
  emptyCard: { alignItems: 'center', padding: 28, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 9 },
  emptyMark: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', backgroundColor: '#141B22' },
  emptyMarkText: { color: colors.volt, fontSize: 22 },
  emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '900', textAlign: 'center' },
  emptyCopy: { color: colors.textMuted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  skeleton: { minHeight: 460, padding: 18, borderRadius: 28, backgroundColor: '#0A0F14', borderWidth: 1, borderColor: colors.border, gap: 16 },
  skeletonHeaderRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 12 },
  skeletonHeaderCopy: { flex: 1, minWidth: 0, gap: 7 },
  skeletonRelic: { alignSelf: 'center' },
  skeletonMetrics: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
});
