import { StyleSheet } from 'react-native';

import { radius, typography } from '@/src/theme';

export const liveStyles = StyleSheet.create({
  root: { gap: 14 },
  header: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerCompact: { minHeight: 40 },
  headerSide: { width: 104, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 7 },
  backText: { ...typography.control, color: '#9CA5B5', letterSpacing: .5 },
  headerTitle: { ...typography.displaySmall, flex: 1, color: '#F7F9FC', fontSize: 24, lineHeight: 26, textAlign: 'center', letterSpacing: -.35 },
  shareButton: { width: 104, minHeight: 44, alignItems: 'flex-end', justifyContent: 'center' },
  arenaFrame: { overflow: 'hidden', padding: 1, borderRadius: 27, boxShadow: '0 18px 44px rgba(0,0,0,.34)' },
  arena: { position: 'relative', overflow: 'hidden', paddingHorizontal: 18, paddingTop: 18, paddingBottom: 17, borderRadius: 26, backgroundColor: '#02060A', gap: 14 },
  arenaCompact: { padding: 14, gap: 10 },
  decorativeBackdrop: { position: 'absolute', inset: 0, pointerEvents: 'none' },
  arenaBeam: { position: 'absolute', top: 40, width: 138, height: 410, opacity: .72 },
  arenaBeamLeft: { left: -78, transform: [{ rotateZ: '-30deg' }] },
  arenaBeamRight: { right: -78, transform: [{ rotateZ: '30deg' }] },
  arenaSeam: { position: 'absolute', top: -70, bottom: -70, left: '49%', width: 44, backgroundColor: 'rgba(0,0,0,.36)', transform: [{ rotateZ: '16deg' }] },
  arenaMeta: { zIndex: 2, minHeight: 24, flexDirection: 'row', alignItems: 'center', gap: 9 },
  arenaEvent: { ...typography.metadata, flex: 1, minWidth: 0, color: '#B6BDCC', letterSpacing: .35 },
  liveStatus: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#FF3A4B', boxShadow: '0 0 10px rgba(255,58,75,.7)' },
  liveText: { ...typography.control, color: '#FF4A58', fontSize: 14, lineHeight: 18, letterSpacing: .5 },
  format: { ...typography.metadata, color: '#B6BDCC', letterSpacing: .6 },
  matchStage: { zIndex: 2, minHeight: 236, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  matchStageCompact: { minHeight: 178 },
  team: { width: '29%', minWidth: 0, alignItems: 'center' },
  teamLogoFrame: { width: 88, height: 88, overflow: 'hidden', borderRadius: 28, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#03090F' },
  teamLogoFrameCompact: { width: 70, height: 70, borderRadius: 23 },
  teamTag: { ...typography.displayMedium, maxWidth: '100%', marginTop: 12, color: '#F8FAFD', fontSize: 31, lineHeight: 31, textAlign: 'center' },
  teamName: { ...typography.body, minHeight: 38, marginTop: 4, color: '#B9C0D0', textAlign: 'center' },
  teamUnderline: { width: 18, height: 2, marginTop: 7, borderRadius: 2, opacity: .72 },
  teamUnderlineRight: { opacity: .85 },
  scoreCenter: { width: '39%', minWidth: 0, alignItems: 'center', justifyContent: 'center' },
  scoreRow: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  score: { ...typography.metricLarge, color: '#FAFBFD', fontSize: 62, lineHeight: 63 },
  scoreDash: { ...typography.bodyComfort, color: '#E5E8ED', fontSize: 24, lineHeight: 28 },
  mapLabel: { ...typography.metadata, marginTop: 11, color: '#98A1B2', letterSpacing: .8 },
  liveClock: { ...typography.displaySmall, marginTop: 1, color: '#F7F9FC', fontSize: 23, lineHeight: 25 },
  community: { zIndex: 2, gap: 11 },
  communityDivider: { height: 1, marginBottom: 4, backgroundColor: 'rgba(173,183,198,.25)' },
  communityTitle: { ...typography.metadata, color: '#A7AFBF', textAlign: 'center', letterSpacing: .9 },
  communityValues: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  communityTag: { ...typography.displaySmall, color: '#F3F5F8', fontSize: 22, lineHeight: 24 },
  communityBar: { position: 'relative', height: 34, overflow: 'hidden', padding: 3, borderRadius: radius.pill, borderWidth: 1, borderColor: 'rgba(224,231,239,.65)', backgroundColor: '#071019', boxShadow: '0 0 16px rgba(80,157,255,.18)' },
  communityBarLeft: { position: 'absolute', top: 3, bottom: 3, left: 3, borderTopLeftRadius: 14, borderBottomLeftRadius: 14 },
  communityBarRight: { position: 'absolute', top: 3, right: 3, bottom: 3, borderTopRightRadius: 14, borderBottomRightRadius: 14 },
  communityBarSeam: { position: 'absolute', top: -5, bottom: -5, width: 12, marginLeft: -6, borderRadius: 7, backgroundColor: '#FFFFFF', opacity: .82, boxShadow: '0 0 14px rgba(255,255,255,.95)' },
  communityBarGloss: { position: 'absolute', top: 5, left: 8, right: 8, height: 7, borderRadius: 5, backgroundColor: 'rgba(255,255,255,.22)' },
  projectionMeta: { ...typography.caption, marginTop: 2, color: '#7F899B', textAlign: 'center', letterSpacing: .5 },
  companionFrame: { minHeight: 102, padding: 15, borderRadius: 20, borderWidth: 1, borderColor: '#9B36E5', flexDirection: 'row', alignItems: 'center', gap: 13, overflow: 'hidden', boxShadow: '0 12px 24px rgba(34,6,64,.28)' },
  companionAvatar: { position: 'relative', width: 58, height: 58, borderRadius: 29, borderWidth: 1, borderColor: '#B283EC', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(32,5,64,.52)' },
  companionInitials: { ...typography.displaySmall, color: '#FFFFFF', fontSize: 25, lineHeight: 27 },
  companionOnline: { position: 'absolute', right: 1, bottom: 1, width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: '#4D157F', backgroundColor: '#FF394F' },
  companionCopy: { flex: 1, minWidth: 0 },
  companionEyebrow: { ...typography.eyebrow, color: '#E2D2FA', fontSize: 9, lineHeight: 12, letterSpacing: .5 },
  companionName: { ...typography.cardTitle, marginTop: 3, color: '#FFFFFF', fontSize: 20, lineHeight: 22 },
  companionText: { ...typography.caption, marginTop: 2, color: '#D7C8EA' },
  watchButton: { minHeight: 38, paddingHorizontal: 12, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#FFFFFF' },
  watchButtonText: { ...typography.control, color: '#5E20BE', fontSize: 10, letterSpacing: .2 },
  contract: { padding: 20, borderRadius: 20, borderWidth: 1, borderColor: '#34404A', backgroundColor: '#080D12', gap: 10 },
  contractEyebrow: { ...typography.eyebrow, color: '#E6F000', letterSpacing: .85 },
  contractTitle: { ...typography.displayMedium, color: '#F7F9FC', fontSize: 31, lineHeight: 32, letterSpacing: -.4 },
  contractClosedPill: { alignSelf: 'flex-start', minHeight: 35, paddingHorizontal: 12, borderRadius: radius.pill, borderWidth: 1, borderColor: '#FF354C', flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(53,7,14,.28)' },
  contractClosedText: { ...typography.control, color: '#FF4658', letterSpacing: .65 },
  contractPrediction: { ...typography.control, color: '#E6F000', letterSpacing: .45 },
  contractTiming: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 12 },
  contractTimingText: { ...typography.metadata, flex: 1, color: '#A3ACBC', letterSpacing: .25 },
  contractDivider: { height: 1, marginTop: 1, backgroundColor: '#242D35' },
  rulesButton: { minHeight: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  rulesButtonText: { ...typography.control, color: '#E6F000', letterSpacing: .45 },
  rulesChevronOpen: { transform: [{ rotateZ: '90deg' }] },
  rulesCopy: { ...typography.body, paddingTop: 3, color: '#AEB6C4' },
  closedNotice: { minHeight: 92, padding: 16, borderRadius: 18, borderWidth: 1, borderColor: '#303A44', backgroundColor: '#080D12', flexDirection: 'row', alignItems: 'center', gap: 15 },
  noticeIcon: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: '#E6F000', alignItems: 'center', justifyContent: 'center', backgroundColor: '#080D0D' },
  noticeCopy: { flex: 1, minWidth: 0 },
  noticeTitle: { ...typography.cardTitle, color: '#F7F9FC', letterSpacing: .1 },
  noticeText: { ...typography.body, marginTop: 3, color: '#A9B1C0' },
  pressed: { opacity: .8, transform: [{ scale: .985 }] },
});
