import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  content: { width: '100%', maxWidth: 430, alignSelf: 'center', paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: 60, gap: spacing.lg },
  topBar: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 10 },
  backArrow: { color: colors.text, fontSize: 19, fontWeight: '800' },
  backText: { ...typography.control, color: colors.textMuted, letterSpacing: .5 },
  pickerBackArrow: { color: colors.volt },
  pickerBackText: { color: colors.text, fontSize: 13, letterSpacing: .25 },
  brand: { ...typography.bodyStrong, color: colors.volt, fontSize: 14, letterSpacing: 1 },
  hero: { position: 'relative', overflow: 'hidden', padding: spacing.lg, borderRadius: 30, backgroundColor: '#0D1218', borderWidth: 1, borderColor: '#2B3541', gap: spacing.md },
  heroAccent: { position: 'absolute', top: 0, left: 0, right: 0, height: 2, backgroundColor: colors.volt },
  metaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  metaLeft: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  gameDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.volt },
  metaText: { ...typography.label, color: colors.text, letterSpacing: .35 },
  metaDivider: { ...typography.label, color: colors.textMuted },
  eventText: { ...typography.label, flex: 1, color: colors.textMuted },
  boPill: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: radius.pill, backgroundColor: colors.surfaceElevated },
  boText: { ...typography.label, color: colors.textMuted },
  dateText: { ...typography.metadata, color: colors.textMuted, letterSpacing: .7 },
  dateLive: { color: colors.liveText },
  duel: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: spacing.sm },
  heroTeam: { width: '36%', alignItems: 'center', gap: 7 },
  heroTeamMark: { width: 74, height: 74, borderRadius: 23, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7 },
  heroTeamWinner: { backgroundColor: '#1B2215', borderColor: '#4A5B23' },
  heroTeamTag: { ...typography.metricSmall, color: colors.text },
  heroTeamName: { ...typography.bodyStrong, color: colors.text, textAlign: 'center' },
  heroScore: { ...typography.metric, color: colors.text },
  heroProbability: { ...typography.label, color: colors.textMuted },
  winnerText: { color: colors.volt },
  duelCenter: { alignItems: 'center', gap: 3 },
  vsLabel: { ...typography.metadata, color: colors.textMuted, letterSpacing: .7 },
  vs: { ...typography.metricSmall, color: colors.text },
  kickoff: { ...typography.label, color: colors.textMuted },
  probabilityWrap: { gap: 7 },
  probabilityLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  probabilityText: { ...typography.metadata, color: colors.textMuted },
  probabilityStrong: { color: colors.text, fontFamily: typography.bodyStrong.fontFamily },
  probabilityTrack: { height: 6, overflow: 'hidden', borderRadius: radius.pill, backgroundColor: '#242B34' },
  probabilityFill: { height: '100%', borderRadius: radius.pill, backgroundColor: colors.volt },
  projectionMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', gap: 5 },
  projectionMetaText: { ...typography.caption, color: '#7D8995', letterSpacing: .25 },
  projectionMetaDot: { ...typography.caption, color: '#56616C' },
  contractCard: { padding: spacing.md, borderRadius: radius.lg, backgroundColor: '#0B1015', borderWidth: 1, borderColor: '#2B3540', gap: spacing.sm },
  contractHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  contractEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .8 },
  contractTitle: { ...typography.cardTitle, marginTop: 4, color: colors.text },
  contractPeople: { minWidth: 70, minHeight: 48, paddingHorizontal: 8, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#151C11', borderWidth: 1, borderColor: '#414D1E' },
  contractPeopleValue: { ...typography.bodyStrong, color: colors.volt },
  contractPeopleLabel: { ...typography.metadata, marginTop: 1, color: colors.textMuted },
  contractCopy: { ...typography.body, color: colors.textMuted },
  contractTiming: { minHeight: 39, paddingHorizontal: 10, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, backgroundColor: '#080C10' },
  contractTimingLabel: { ...typography.metadata, color: colors.textMuted, letterSpacing: .35 },
  contractTimingValue: { ...typography.metadata, color: colors.text },
  contractHidden: { minHeight: 43, paddingHorizontal: 10, borderRadius: 13, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#0D1217', borderWidth: 1, borderColor: '#252E37' },
  contractHiddenGlyph: { color: '#73808B', fontSize: 17 },
  contractHiddenText: { ...typography.caption, flex: 1, color: colors.textMuted },
  contractDistribution: { padding: 10, borderRadius: 14, gap: 7, backgroundColor: '#0D1217', borderWidth: 1, borderColor: '#29333C' },
  contractDistributionTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  contractDistributionLabel: { ...typography.metadata, color: colors.volt, letterSpacing: .35 },
  contractDistributionTotal: { ...typography.metadata, color: colors.textMuted },
  contractDistributionValues: { flexDirection: 'row', justifyContent: 'space-between' },
  contractDistributionA: { ...typography.bodyStrong, color: '#65B7FF' },
  contractDistributionB: { ...typography.bodyStrong, color: '#FF6C7C' },
  contractDistributionTrack: { height: 6, borderRadius: 3, overflow: 'hidden', backgroundColor: '#FF6C7C' },
  contractDistributionFill: { height: '100%', backgroundColor: '#65B7FF' },
  contractSource: { minHeight: 40, paddingHorizontal: 10, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, backgroundColor: '#080C10' },
  contractSourceLabel: { ...typography.metadata, color: colors.textMuted, letterSpacing: .35 },
  contractSourceCopy: { flex: 1, minWidth: 0, alignItems: 'flex-end' },
  contractSourceValue: { ...typography.caption, color: colors.text },
  contractSourceReference: { ...typography.eyebrow, maxWidth: '100%', marginTop: 2, color: colors.textSubtle, letterSpacing: .2 },
  market: { gap: spacing.md },
  marketTitle: { ...typography.displaySmall, color: colors.text, fontSize: 31, lineHeight: 33, letterSpacing: -.35 },
  marketCopy: { ...typography.body, paddingHorizontal: 8, color: colors.textMuted, textAlign: 'center' },
  choiceGrid: { flexDirection: 'row', gap: 12 },
  choice: { position: 'relative', flex: 1, minWidth: 0, minHeight: 224, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 18, borderRadius: 18, backgroundColor: '#0A0F14', borderWidth: 1, borderColor: '#53606B', alignItems: 'center', justifyContent: 'flex-end', gap: 12, outlineStyle: 'solid', outlineWidth: 2, outlineColor: 'transparent' },
  choiceFocused: { outlineColor: '#96A2AD' },
  choiceSelected: { borderWidth: 1.5, borderColor: colors.volt, outlineColor: colors.volt, boxShadow: `0 0 22px ${colors.volt}28` },
  choiceGradient: { ...StyleSheet.absoluteFill },
  choiceCheck: { position: 'absolute', top: 12, right: 12, width: 21, height: 21, borderRadius: 11, backgroundColor: colors.volt, alignItems: 'center', justifyContent: 'center', boxShadow: `0 0 12px ${colors.volt}55` },
  choiceLogo: { flex: 1, minHeight: 118, alignItems: 'center', justifyContent: 'center' },
  choiceTag: { ...typography.displaySmall, color: colors.text, fontSize: 28, lineHeight: 30 },
  selectionOutcome: { overflow: 'hidden', borderRadius: 18, backgroundColor: '#0B100D', borderWidth: 1, borderColor: '#303A24' },
  selectionOutcomeHeader: { minHeight: 42, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, borderBottomWidth: 1, borderBottomColor: '#252D20' },
  selectionOutcomeEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .8 },
  selectionOutcomeMeta: { ...typography.metadata, color: colors.textMuted, letterSpacing: .25 },
  lockCountdown: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  lockCountdownLabel: { ...typography.metadata, color: colors.textMuted, letterSpacing: .7 },
  lockCountdownValue: { ...typography.control, color: colors.volt, letterSpacing: .45 },
  ticket: { gap: spacing.sm },
  riskRow: { minHeight: 78, flexDirection: 'row', alignItems: 'stretch', backgroundColor: '#080C0A', overflow: 'hidden' },
  riskCell: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  riskDivider: { width: 1, marginVertical: 12, backgroundColor: '#303A24' },
  riskLabel: { ...typography.metadata, color: colors.textMuted, letterSpacing: .7 },
  riskValue: { ...typography.metricSmall, marginTop: 3 },
  riskGain: { color: colors.volt },
  riskLoss: { color: '#FF727E' },
  riskUnitRow: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  riskUnit: { ...typography.caption, color: colors.textMuted },
  submitError: { padding: spacing.sm, borderRadius: radius.sm, backgroundColor: '#1A1012', borderWidth: 1, borderColor: '#4A2027', gap: 4 },
  submitErrorTitle: { ...typography.control, color: colors.liveText, letterSpacing: .4 },
  submitErrorCopy: { ...typography.body, color: '#D78891' },
  confirmPressed: { opacity: .85 },
  lockedCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#101510', borderWidth: 1, borderColor: '#3A4722', gap: spacing.md },
  lockedCardWin: { borderColor: '#315D3D', backgroundColor: '#0D1711' },
  lockedCardLoss: { borderColor: '#5A2B32', backgroundColor: '#171012' },
  lockedHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  lockedEyebrow: { ...typography.metadata, color: colors.volt, fontFamily: typography.control.fontFamily, letterSpacing: .9 },
  lockedEyebrowLoss: { color: '#FF8C97' },
  lockedTeam: { ...typography.sectionTitle, marginTop: 5, color: colors.text },
  lockedBadge: { minWidth: 46, height: 46, paddingHorizontal: 7, borderRadius: 14, backgroundColor: colors.volt, alignItems: 'center', justifyContent: 'center' },
  lockedBadgeText: { ...typography.action, color: '#080B0F' },
  lockedMeta: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  lockedModel: { ...typography.metadata, color: colors.textMuted },
  lockedDot: { ...typography.label, color: colors.textMuted },
  verdictLine: { paddingTop: 12, borderTopWidth: 1, borderTopColor: '#303A24', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  verdictLabel: { ...typography.metadata, color: colors.textMuted, letterSpacing: .7 },
  verdictValue: { ...typography.control, flex: 1, textAlign: 'right', color: colors.text },
  verdictWin: { color: colors.success },
  verdictLoss: { color: colors.danger },
  lockedOutcomeCopy: { ...typography.body, color: colors.textMuted },
  callTimeline: { minHeight: 96, paddingHorizontal: 8, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#090D0A', borderWidth: 1, borderColor: '#2D3720' },
  timelineStep: { flex: 1, minWidth: 0, alignItems: 'center' },
  timelineDot: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#171D18', borderWidth: 1, borderColor: '#303A32' },
  timelineDotComplete: { backgroundColor: colors.volt, borderColor: colors.volt },
  timelineDotText: { ...typography.label, color: colors.textMuted },
  timelineDotTextComplete: { color: '#080B0F' },
  timelineLabel: { ...typography.metadata, marginTop: 4, color: colors.textMuted, letterSpacing: .25 },
  timelineLabelComplete: { color: colors.text },
  timelineMeta: { ...typography.metadata, marginTop: 2, maxWidth: 82, color: colors.textMuted, textAlign: 'center' },
  timelineArrow: { marginHorizontal: -2, color: '#45502B', fontSize: 11, fontWeight: '900' },
  lockedActions: { flexDirection: 'row', gap: spacing.sm },
  lockedPrimaryAction: { flex: 1, minHeight: 46, paddingHorizontal: 10, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.volt },
  lockedPrimaryText: { ...typography.control, color: '#080B0F', letterSpacing: .3, textAlign: 'center' },
  lockedSecondaryAction: { flex: 1, minHeight: 46, paddingHorizontal: 10, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0A0F0B', borderWidth: 1, borderColor: '#3B4725' },
  lockedSecondaryText: { ...typography.control, color: colors.volt, letterSpacing: .3, textAlign: 'center' },
  duelAction: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#11170E', borderWidth: 1, borderColor: '#414D1E', gap: spacing.md },
  duelActionCopy: { gap: 6 },
  duelActionEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .9 },
  duelActionTitle: { ...typography.cardTitle, color: colors.text },
  duelActionText: { ...typography.body, color: colors.textMuted },
  duelActionError: { ...typography.body, color: '#FF9AA3' },
  duelActionButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.volt },
  duelActionButtonText: { ...typography.control, color: '#080B0F', letterSpacing: .4 },
  closedCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 8 },
  closedEyebrow: { ...typography.metadata, color: colors.textMuted, fontFamily: typography.control.fontFamily, letterSpacing: 1 },
  closedTitle: { ...typography.cardTitle, color: colors.text },
  closedCopy: { ...typography.body, color: colors.textMuted },
  infoCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#090D11', borderWidth: 1, borderColor: colors.border, gap: 7 },
  infoEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .9 },
  infoTitle: { ...typography.cardTitle, color: colors.text },
  infoCopy: { ...typography.body, color: colors.textMuted },
  relatedSection: { gap: 12 },
  relatedEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .9 },
  relatedTitle: { ...typography.sectionTitle, marginTop: 4, color: colors.text },
  relatedRail: { gap: spacing.sm },
  relatedCard: { width: 224, minHeight: 166, padding: 14, borderRadius: 18, backgroundColor: '#0A0F14', borderWidth: 1, borderColor: colors.border },
  relatedTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  relatedWhen: { ...typography.label, color: colors.volt, letterSpacing: .25 },
  relatedGame: { ...typography.label, color: colors.textMuted },
  relatedEvent: { ...typography.caption, marginTop: 10, color: colors.textMuted },
  relatedDuel: { ...typography.metricSmall, marginTop: 10, color: colors.text },
  relatedVs: { ...typography.label, color: colors.textMuted },
  relatedFooter: { marginTop: 'auto', paddingTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#1D252D' },
  relatedFormat: { ...typography.label, color: colors.textMuted, letterSpacing: .35 },
  relatedArrow: { color: colors.volt, fontSize: 16, fontWeight: '900' },
  loadingStack: { gap: 12 },
  loadingCard: { height: 290, padding: spacing.lg, borderRadius: 30, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 12 },
  loadingMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  loadingEvent: { ...typography.label, flex: 1, color: colors.textMuted },
  loadingFormat: { ...typography.label, minHeight: 24, paddingHorizontal: 9, borderRadius: radius.pill, color: colors.textMuted, backgroundColor: colors.surfaceElevated, textAlignVertical: 'center' },
  loadingGame: { ...typography.metadata, color: colors.textMuted, letterSpacing: .7 },
  loadingDuel: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', gap: 10 },
  loadingTeam: { width: 82, alignItems: 'center', gap: 8 },
  loadingTeamMark: { width: 72, height: 72, borderRadius: 23, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border },
  loadingTeamTag: { ...typography.metricSmall, color: colors.text },
  loadingTeamName: { ...typography.bodyStrong, color: colors.text, textAlign: 'center' },
  loadingVersus: { width: 52, alignItems: 'center', gap: 8 },
  loadingVs: { ...typography.metricSmall, color: colors.text },
  loadingMarket: { minHeight: 218, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surfaceLow, borderWidth: 1, borderColor: colors.borderSubtle, gap: 14 },
  loadingChoices: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  pressed: { opacity: .82, transform: [{ scale: .99 }] },
});
