import { StyleSheet } from 'react-native';

import { colors, fonts, layout, spacing, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  gameBackground: { position: 'absolute', inset: 0, overflow: 'hidden', backgroundColor: '#020609' },
  gameBackgroundImage: { position: 'absolute', inset: 0, width: '100%', height: '100%' },
  gameBackgroundScrim: { position: 'absolute', inset: 0 },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingBottom: layout.tabBarContentInset, gap: 14 },
  targetedDuelBanner: { minHeight: 84, marginHorizontal: spacing.md, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, backgroundColor: 'rgba(18,25,11,.76)', borderWidth: 1, borderColor: '#4A5720' }, targetedDuelCopy: { flex: 1, minWidth: 0 }, targetedDuelEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .75 }, targetedDuelTitle: { ...typography.bodyStrong, marginTop: 5, color: colors.text }, targetedDuelClose: { width: layout.minTouchTarget, height: layout.minTouchTarget, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(8,13,7,.74)', borderWidth: 1, borderColor: '#35401B' }, targetedDuelCloseText: { color: colors.textMuted, fontSize: 23, lineHeight: 24 },
  scheduleHero: { position: 'relative', minHeight: 158, marginHorizontal: spacing.md, overflow: 'hidden', borderRadius: 23, backgroundColor: 'rgba(7,14,20,.68)', borderWidth: 1, borderColor: 'rgba(121,150,171,.38)', padding: 12, paddingBottom: 20 },
  scheduleHeroLandscape: { minHeight: 138, padding: 10, paddingBottom: 16, borderRadius: 20 },
  scheduleTop: { zIndex: 2, minHeight: layout.minTouchTarget, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  scheduleHeading: { flex: 1, minWidth: 0, gap: 1 },
  searchField: { flex: 1, height: layout.minTouchTarget, paddingHorizontal: 11, borderRadius: 22, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(5,9,12,.74)', borderWidth: 1, borderColor: 'rgba(255,255,255,.26)' },
  searchInput: { ...typography.bodyStrong, flex: 1, color: '#FFFFFF' },
  scheduleActions: { flexDirection: 'row', gap: 6 },
  iconButton: { width: layout.minTouchTarget, height: layout.minTouchTarget, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(5,9,12,.52)', borderWidth: 1, borderColor: 'rgba(255,255,255,.17)' },
  scheduleTitle: { ...typography.cardTitle, color: '#F8FAFA' },
  scheduleMonth: { ...typography.caption, color: 'rgba(255,255,255,.76)', letterSpacing: .65 },
  daysScroll: { zIndex: 2, flexGrow: 0, flexShrink: 0, marginTop: 'auto' },
  daysRow: { minWidth: '100%', flexGrow: 1, flexDirection: 'row', justifyContent: 'space-between', gap: 5 },
  dayButton: { width: layout.minTouchTarget, minWidth: layout.minTouchTarget, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(234,244,216,.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,.09)' },
  dayButtonLandscape: { height: layout.minTouchTarget, borderRadius: 15 },
  dayButtonActive: { backgroundColor: '#F5F6F0', borderColor: '#FFFFFF' },
  dayButtonPressed: { transform: [{ scale: .96 }] },
  dayName: { ...typography.label, color: 'rgba(255,255,255,.72)' },
  dayNumber: { ...typography.bodyStrong, marginTop: 1, color: '#FFFFFF' },
  dayTextActive: { color: '#0A0E11' },
  dayMatchDot: { width: 4, height: 4, marginTop: 1, borderRadius: 2, backgroundColor: 'transparent' },
  dayMatchDotVisible: { backgroundColor: colors.volt },
  dayMatchDotActive: { backgroundColor: '#0A0E11' },
  filterPanel: { marginHorizontal: spacing.md, padding: 7, borderRadius: 20, backgroundColor: 'rgba(7,13,18,.74)', borderWidth: 1, borderColor: 'rgba(97,119,136,.30)', gap: 7 },
  gameRow: { flexDirection: 'row', gap: 5 },
  gameFilter: { flex: 1, minHeight: 44, paddingHorizontal: 5, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  gameFilterActive: { backgroundColor: 'rgba(21,27,16,.78)', borderWidth: 1, borderColor: '#47531F' },
  gameIcon: { width: 23, height: 23, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(21,27,33,.78)' },
  gameIconActive: { backgroundColor: colors.volt },
  allGamesGlyph: { color: '#8B96A2', fontFamily: fonts.display, fontSize: 14 },
  allGamesGlyphActive: { color: '#070A0E' },
  gameFilterText: { ...typography.label, color: colors.textMuted, letterSpacing: .25 },
  gameFilterTextActive: { color: '#F4F6F7' },
  modeRow: { minHeight: 52, flexDirection: 'row', gap: 7 },
  callsModeInfo: { flex: 1, minHeight: 44, paddingHorizontal: 12, borderRadius: 14, justifyContent: 'center', backgroundColor: 'rgba(4,9,13,.68)', borderWidth: 1, borderColor: '#28321C' },
  callsModeInfoText: { ...typography.label, color: colors.volt, letterSpacing: .35 },
  callsModeInfoMeta: { ...typography.caption, marginTop: 1, color: '#78845D' },
  statusSwitch: { flex: 1, minHeight: 50, padding: 3, borderRadius: 14, flexDirection: 'row', backgroundColor: 'rgba(4,9,13,.66)', borderWidth: 1, borderColor: '#202832' },
  statusButton: { flex: 1, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  statusButtonActive: { backgroundColor: 'rgba(43,55,66,.72)' },
  statusText: { ...typography.label, color: colors.textMuted, letterSpacing: .25 },
  statusTextActive: { color: '#F5F7F8' },
  callsButton: { minWidth: 118, paddingHorizontal: 9, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: 'rgba(4,9,13,.66)', borderWidth: 1, borderColor: '#202832' },
  callsButtonActive: { backgroundColor: 'rgba(22,29,15,.78)', borderColor: '#4B5820' },
  callsDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#4B5661' },
  callsDotActive: { backgroundColor: colors.volt },
  callsButtonCopy: { minWidth: 0 },
  callsText: { ...typography.label, color: colors.textMuted, letterSpacing: .2 },
  callsTextActive: { color: colors.volt },
  callsCount: { ...typography.caption, marginTop: 1, color: '#596570' },
  callsCountActive: { color: '#AEBB73' },
  adminLink: { minHeight: layout.minTouchTarget, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#202832' },
  adminLinkText: { ...typography.action, color: colors.textMuted, letterSpacing: .5 },
  adminLinkArrow: { color: colors.volt, fontSize: 14 },
  stateInset: { marginHorizontal: spacing.md },
  matchesSection: { marginHorizontal: spacing.md, gap: 12 },
  sectionHead: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  sectionEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: 1.1 },
  sectionTitle: { ...typography.sectionTitle, marginTop: 4, color: colors.text },
  countPill: { minHeight: 27, paddingHorizontal: 10, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(10,16,22,.68)', borderWidth: 1, borderColor: '#29323B' },
  countText: { ...typography.label, color: colors.textSubtle, letterSpacing: .4 },
  liveStack: { gap: 10 },
  liveCard: { minHeight: 240, overflow: 'hidden', borderRadius: 26, backgroundColor: 'rgba(7,14,20,.68)', borderWidth: 1, borderColor: 'rgba(121,150,171,.42)', padding: 15 },
  liveTop: { zIndex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  liveEvent: { ...typography.label, flex: 1, color: 'rgba(255,255,255,.76)', letterSpacing: .35 },
  livePill: { minHeight: 28, paddingHorizontal: 10, borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.liveSurface, borderWidth: 1, borderColor: colors.liveBorder },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.live },
  liveText: { ...typography.eyebrow, color: colors.liveText, letterSpacing: .7 },
  liveDuel: { zIndex: 2, marginTop: 25, flexDirection: 'row', alignItems: 'flex-start', gap: 16 },
  matchTeam: { flex: 1, minWidth: 0, alignItems: 'center', gap: 7 },
  matchTeamName: { ...typography.bodyStrong, width: '100%', minHeight: 36, color: '#FFFFFF', textAlign: 'center', fontSize: 14, lineHeight: 18 },
  matchTeamNameCompact: { minHeight: 32, fontSize: 12, lineHeight: 16 },
  liveScore: { minWidth: 66, flexShrink: 0, alignItems: 'center' },
  liveBo: { ...typography.eyebrow, color: 'rgba(255,255,255,.58)', letterSpacing: .7 },
  liveScoreText: { ...typography.displayMedium, marginTop: 5, color: '#FFFFFF' },
  liveFooter: { zIndex: 2, minHeight: 38, marginTop: 'auto', paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.13)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  liveFooterText: { ...typography.action, color: '#D5DBDF', letterSpacing: .7 },
  liveFooterCall: { color: colors.volt },
  liveFooterArrow: { color: colors.volt, fontSize: 17 },
  matchList: { overflow: 'hidden', borderRadius: 20, backgroundColor: 'rgba(7,13,18,.72)', borderWidth: 1, borderColor: 'rgba(97,119,136,.30)' },
  matchRow: { minHeight: 140, padding: 11, gap: 10, borderBottomWidth: 1, borderBottomColor: '#192129' },
  rowHeader: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  rowWhen: { width: 43 },
  rowTime: { ...typography.bodyStrong, color: '#F3F6F7' },
  rowGame: { ...typography.caption, marginTop: 3, color: colors.textMuted },
  rowEvent: { ...typography.caption, flex: 1, minWidth: 0, color: colors.textMuted },
  rowDuel: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  rowScore: { minWidth: 56, minHeight: 42, alignItems: 'center', justifyContent: 'center' },
  rowTeams: { ...typography.bodyStrong, color: colors.text },
  rowTrailing: { minWidth: 58, alignItems: 'flex-end', gap: 2 },
  rowState: { ...typography.label, color: colors.textMuted, letterSpacing: .15 },
  rowStateAccent: { color: colors.volt },
  rowStateLoss: { color: colors.danger },
  rowArrow: { color: colors.volt, fontSize: 16 },
  skeleton: { marginHorizontal: spacing.md, gap: 10 },
  skeletonHead: { minHeight: 43, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  skeletonHeadCopy: { flex: 1, gap: 6 },
  skeletonList: { overflow: 'hidden', borderRadius: 20, backgroundColor: 'rgba(7,13,18,.72)', borderWidth: 1, borderColor: 'rgba(97,119,136,.30)' },
  skeletonRow: { minHeight: 98, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 9 },
  skeletonRowDivider: { borderTopWidth: 1, borderTopColor: '#192129' },
  skeletonWhen: { width: 43, gap: 6 },
  skeletonLogos: { width: 52, flexDirection: 'row', alignItems: 'center' },
  skeletonLogoOverlap: { marginLeft: -15 },
  skeletonRowCopy: { flex: 1, minWidth: 0, gap: 8 },
  pressed: { opacity: .76 },
});
