import { StyleSheet } from 'react-native';

import { colors, fonts, layout, radius, spacing, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingBottom: layout.tabBarContentInset, gap: 14 },
  targetedDuelBanner: { minHeight: 84, marginHorizontal: spacing.md, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, backgroundColor: '#171E10', borderWidth: 1, borderColor: '#4A5720' }, targetedDuelCopy: { flex: 1, minWidth: 0 }, targetedDuelEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .75 }, targetedDuelTitle: { ...typography.bodyStrong, marginTop: 5, color: colors.text }, targetedDuelClose: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#0D120C', borderWidth: 1, borderColor: '#35401B' }, targetedDuelCloseText: { color: colors.textMuted, fontSize: 23, lineHeight: 24 },
  scheduleHero: { position: 'relative', minHeight: 244, marginHorizontal: spacing.md, overflow: 'hidden', borderRadius: 27, backgroundColor: '#101820', borderWidth: 1, borderColor: '#2B3540', padding: 14 },
  scheduleBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, width: '100%', height: '100%' },
  scheduleTop: { zIndex: 2, minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  arenaMark: { minHeight: 31, paddingHorizontal: 10, borderRadius: 16, flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: 'rgba(5,9,12,.48)', borderWidth: 1, borderColor: 'rgba(255,255,255,.16)' },
  arenaMarkDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.volt },
  arenaMarkText: { ...typography.eyebrow, color: '#F4F7F8', letterSpacing: 1 },
  searchField: { flex: 1, height: 36, paddingHorizontal: 11, borderRadius: 18, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(5,9,12,.74)', borderWidth: 1, borderColor: 'rgba(255,255,255,.26)' },
  searchInput: { ...typography.bodyStrong, flex: 1, color: '#FFFFFF' },
  scheduleActions: { flexDirection: 'row', gap: 8 },
  iconButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(5,9,12,.52)', borderWidth: 1, borderColor: 'rgba(255,255,255,.17)' },
  scheduleCopy: { zIndex: 2, marginTop: 'auto', marginBottom: 10, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  scheduleTitle: { ...typography.displaySmall, maxWidth: 275, color: '#F8FAFA' },
  scheduleMonth: { ...typography.eyebrow, marginBottom: 3, color: 'rgba(255,255,255,.76)', letterSpacing: .7 },
  daysRow: { zIndex: 2, flexDirection: 'row', gap: 5 },
  dayButton: { flex: 1, minWidth: 0, height: 55, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(234,244,216,.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,.09)' },
  dayButtonActive: { backgroundColor: '#F5F6F0', borderColor: '#FFFFFF' },
  dayButtonPressed: { transform: [{ scale: .96 }] },
  dayName: { ...typography.label, color: 'rgba(255,255,255,.72)' },
  dayNumber: { ...typography.bodyStrong, marginTop: 3, color: '#FFFFFF' },
  dayTextActive: { color: '#0A0E11' },
  dayMatchDot: { width: 4, height: 4, marginTop: 3, borderRadius: 2, backgroundColor: 'transparent' },
  dayMatchDotVisible: { backgroundColor: colors.volt },
  dayMatchDotActive: { backgroundColor: '#0A0E11' },
  filterPanel: { marginHorizontal: spacing.md, padding: 7, borderRadius: 20, backgroundColor: '#0B1015', borderWidth: 1, borderColor: '#222B34', gap: 7 },
  gameRow: { flexDirection: 'row', gap: 5 },
  gameFilter: { flex: 1, minHeight: 44, paddingHorizontal: 5, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  gameFilterActive: { backgroundColor: '#151B10', borderWidth: 1, borderColor: '#47531F' },
  gameIcon: { width: 23, height: 23, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#151B21' },
  gameIconActive: { backgroundColor: colors.volt },
  allGamesGlyph: { color: '#8B96A2', fontFamily: fonts.display, fontSize: 14 },
  allGamesGlyphActive: { color: '#070A0E' },
  gameFilterText: { ...typography.label, color: colors.textMuted, letterSpacing: .25 },
  gameFilterTextActive: { color: '#F4F6F7' },
  modeRow: { minHeight: 46, flexDirection: 'row', gap: 7 },
  callsModeInfo: { flex: 1, minHeight: 44, paddingHorizontal: 12, borderRadius: 14, justifyContent: 'center', backgroundColor: '#070B0F', borderWidth: 1, borderColor: '#28321C' },
  callsModeInfoText: { ...typography.label, color: colors.volt, letterSpacing: .35 },
  callsModeInfoMeta: { ...typography.caption, marginTop: 1, color: '#78845D' },
  statusSwitch: { flex: 1, minHeight: 44, padding: 3, borderRadius: 14, flexDirection: 'row', backgroundColor: '#070B0F', borderWidth: 1, borderColor: '#202832' },
  statusButton: { flex: 1, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  statusButtonActive: { backgroundColor: '#202830' },
  statusText: { ...typography.label, color: colors.textMuted, letterSpacing: .25 },
  statusTextActive: { color: '#F5F7F8' },
  callsButton: { minWidth: 118, paddingHorizontal: 9, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: '#070B0F', borderWidth: 1, borderColor: '#202832' },
  callsButtonActive: { backgroundColor: '#161D0F', borderColor: '#4B5820' },
  callsDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#4B5661' },
  callsDotActive: { backgroundColor: colors.volt },
  callsButtonCopy: { minWidth: 0 },
  callsText: { ...typography.label, color: colors.textMuted, letterSpacing: .2 },
  callsTextActive: { color: colors.volt },
  callsCount: { ...typography.caption, marginTop: 1, color: '#596570' },
  callsCountActive: { color: '#AEBB73' },
  adminLink: { minHeight: 34, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#202832' },
  adminLinkText: { ...typography.action, color: colors.textMuted, letterSpacing: .5 },
  adminLinkArrow: { color: colors.volt, fontSize: 14 },
  errorCard: { marginHorizontal: spacing.md, padding: 13, borderRadius: radius.md, backgroundColor: '#1A1012', borderWidth: 1, borderColor: '#4A2027', flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  errorText: { ...typography.body, flex: 1, color: '#FF9AA2' },
  retry: { ...typography.action, color: colors.volt },
  matchesSection: { marginHorizontal: spacing.md, gap: 12 },
  sectionHead: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  sectionEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: 1.1 },
  sectionTitle: { ...typography.sectionTitle, marginTop: 4, color: colors.text },
  countPill: { minHeight: 27, paddingHorizontal: 10, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#11171D', borderWidth: 1, borderColor: '#29323B' },
  countText: { ...typography.label, color: colors.textSubtle, letterSpacing: .4 },
  liveStack: { gap: 10 },
  liveCard: { minHeight: 240, overflow: 'hidden', borderRadius: 26, backgroundColor: '#111820', borderWidth: 1, borderColor: '#394550', padding: 15 },
  liveBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, width: '100%', height: '100%' },
  liveTop: { zIndex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  liveEvent: { ...typography.label, flex: 1, color: 'rgba(255,255,255,.76)', letterSpacing: .35 },
  livePill: { minHeight: 28, paddingHorizontal: 10, borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.liveSurface, borderWidth: 1, borderColor: colors.liveBorder },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.live },
  liveText: { ...typography.eyebrow, color: colors.liveText, letterSpacing: .7 },
  liveDuel: { zIndex: 2, marginTop: 25, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 28 },
  liveTeam: { width: 74, alignItems: 'center', gap: 7 },
  liveTeamTag: { ...typography.bodyStrong, color: '#FFFFFF' },
  liveScore: { alignItems: 'center' },
  liveBo: { ...typography.eyebrow, color: 'rgba(255,255,255,.58)', letterSpacing: .7 },
  liveScoreText: { ...typography.displayMedium, marginTop: 5, color: '#FFFFFF' },
  liveFooter: { zIndex: 2, minHeight: 38, marginTop: 'auto', paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.13)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  liveFooterText: { ...typography.action, color: '#D5DBDF', letterSpacing: .7 },
  liveFooterCall: { color: colors.volt },
  liveFooterArrow: { color: colors.volt, fontSize: 17 },
  matchList: { overflow: 'hidden', borderRadius: 20, backgroundColor: '#0B1015', borderWidth: 1, borderColor: '#222B34' },
  matchRow: { minHeight: 98, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: '#192129' },
  rowWhen: { width: 43 },
  rowTime: { ...typography.bodyStrong, color: '#F3F6F7' },
  rowGame: { ...typography.caption, marginTop: 3, color: colors.textMuted },
  rowLogos: { width: 52, flexDirection: 'row', alignItems: 'center' },
  rowLogoOverlap: { marginLeft: -15 },
  rowMain: { flex: 1, minWidth: 0 },
  rowEvent: { ...typography.caption, color: colors.textMuted },
  rowTeams: { ...typography.bodyStrong, marginTop: 5, color: colors.text },
  rowTrailing: { minWidth: 58, alignItems: 'flex-end', gap: 2 },
  rowState: { ...typography.label, color: colors.textMuted, letterSpacing: .15 },
  rowStateAccent: { color: colors.volt },
  rowStateLoss: { color: colors.danger },
  rowArrow: { color: colors.volt, fontSize: 16 },
  emptyCard: { minHeight: 210, marginHorizontal: spacing.md, justifyContent: 'center', padding: 24, borderRadius: 26, backgroundColor: '#0B1015', borderWidth: 1, borderColor: '#252E37' },
  emptyEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: 1.3 },
  emptyTitle: { ...typography.displaySmall, marginTop: 10, color: colors.text },
  emptyCopy: { ...typography.body, marginTop: 10, color: colors.textMuted },
  skeleton: { marginHorizontal: spacing.md, gap: 10 },
  skeletonHead: { width: 180, height: 30, borderRadius: 12, backgroundColor: '#131A21' },
  skeletonRow: { height: 88, borderRadius: 20, backgroundColor: '#10161C', borderWidth: 1, borderColor: '#202832' },
  pressed: { opacity: .76 },
});
