import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  content: { width: '100%', maxWidth: 430, alignSelf: 'center', paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: 60, gap: spacing.lg },
  topBar: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backButton: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 10 },
  backArrow: { color: colors.text, fontSize: 19, fontWeight: '800' },
  backText: { ...typography.action, color: colors.textMuted, letterSpacing: .5 },
  brand: { ...typography.bodyStrong, color: colors.volt, fontSize: 14, letterSpacing: 1 },
  hero: { position: 'relative', overflow: 'hidden', padding: spacing.lg, borderRadius: 30, backgroundColor: '#0D1218', borderWidth: 1, borderColor: '#2B3541', gap: spacing.md },
  heroAccent: { position: 'absolute', top: 0, left: 0, right: 0, height: 2, backgroundColor: colors.volt },
  metaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  metaLeft: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  gameDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.volt },
  metaText: { ...typography.label, color: colors.text, letterSpacing: .35 },
  metaDivider: { ...typography.label, color: colors.textMuted },
  eventText: { ...typography.label, flex: 1, color: colors.textMuted },
  boPill: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: radius.pill, backgroundColor: colors.surfaceElevated },
  boText: { ...typography.label, color: colors.textMuted },
  dateText: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .7 },
  dateLive: { color: colors.liveText },
  duel: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: spacing.sm },
  heroTeam: { width: '36%', alignItems: 'center', gap: 7 },
  heroTeamMark: { width: 74, height: 74, borderRadius: 23, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7 },
  heroTeamWinner: { backgroundColor: '#1B2215', borderColor: '#4A5B23' },
  heroTeamTag: { ...typography.metricSmall, color: colors.text },
  heroTeamName: { ...typography.bodyStrong, color: colors.text, textAlign: 'center' },
  heroScore: { ...typography.metric, color: colors.text },
  heroProbability: { ...typography.label, color: colors.textMuted },
  winnerText: { color: colors.volt },
  duelCenter: { alignItems: 'center', gap: 3 },
  vsLabel: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .7 },
  vs: { ...typography.metricSmall, color: colors.text },
  kickoff: { ...typography.label, color: colors.textMuted },
  probabilityWrap: { gap: 7 },
  probabilityLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  probabilityText: { ...typography.label, color: colors.textMuted },
  probabilityStrong: { color: colors.text, fontFamily: typography.bodyStrong.fontFamily },
  probabilityTrack: { height: 6, overflow: 'hidden', borderRadius: radius.pill, backgroundColor: '#242B34' },
  probabilityFill: { height: '100%', borderRadius: radius.pill, backgroundColor: colors.volt },
  projectionMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', gap: 5 },
  projectionMetaText: { ...typography.caption, color: '#7D8995', letterSpacing: .25 },
  projectionMetaDot: { ...typography.caption, color: '#56616C' },
  contractCard: { padding: spacing.md, borderRadius: radius.lg, backgroundColor: '#0B1015', borderWidth: 1, borderColor: '#2B3540', gap: spacing.sm },
  contractHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  contractEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .8 },
  contractTitle: { ...typography.cardTitle, marginTop: 4, color: colors.text },
  contractPeople: { minWidth: 58, minHeight: 48, paddingHorizontal: 8, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#151C11', borderWidth: 1, borderColor: '#414D1E' },
  contractPeopleValue: { ...typography.bodyStrong, color: colors.volt },
  contractPeopleLabel: { ...typography.label, marginTop: 1, color: colors.textMuted, fontSize: 9 },
  contractCopy: { ...typography.body, color: colors.textMuted },
  contractTiming: { minHeight: 39, paddingHorizontal: 10, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, backgroundColor: '#080C10' },
  contractTimingLabel: { ...typography.label, color: '#73808B', letterSpacing: .35 },
  contractTimingValue: { ...typography.caption, color: colors.text },
  contractHidden: { minHeight: 43, paddingHorizontal: 10, borderRadius: 13, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#0D1217', borderWidth: 1, borderColor: '#252E37' },
  contractHiddenGlyph: { color: '#73808B', fontSize: 17 },
  contractHiddenText: { ...typography.caption, flex: 1, color: colors.textMuted },
  contractDistribution: { padding: 10, borderRadius: 14, gap: 7, backgroundColor: '#0D1217', borderWidth: 1, borderColor: '#29333C' },
  contractDistributionTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  contractDistributionLabel: { ...typography.label, color: colors.volt, letterSpacing: .35 },
  contractDistributionTotal: { ...typography.label, color: '#73808B' },
  contractDistributionValues: { flexDirection: 'row', justifyContent: 'space-between' },
  contractDistributionA: { ...typography.bodyStrong, color: '#65B7FF' },
  contractDistributionB: { ...typography.bodyStrong, color: '#FF6C7C' },
  contractDistributionTrack: { height: 6, borderRadius: 3, overflow: 'hidden', backgroundColor: '#FF6C7C' },
  contractDistributionFill: { height: '100%', backgroundColor: '#65B7FF' },
  contractSource: { minHeight: 40, paddingHorizontal: 10, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, backgroundColor: '#080C10' },
  contractSourceLabel: { ...typography.label, color: '#73808B', letterSpacing: .35 },
  contractSourceCopy: { flex: 1, minWidth: 0, alignItems: 'flex-end' },
  contractSourceValue: { ...typography.caption, color: colors.text },
  contractSourceReference: { ...typography.eyebrow, maxWidth: '100%', marginTop: 2, color: colors.textSubtle, letterSpacing: .2 },
  market: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#0A0F14', borderWidth: 1, borderColor: colors.border, gap: 8 },
  marketEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: 1.1 },
  marketTitle: { ...typography.sectionTitle, color: colors.text },
  marketCopy: { ...typography.body, color: colors.textMuted },
  choiceGrid: { marginTop: 8, flexDirection: 'row', gap: 10 },
  choice: { flex: 1, minWidth: 0, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 7 },
  choiceSelected: { backgroundColor: '#171E12', borderColor: colors.volt },
  choiceMark: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceElevated },
  choiceMarkSelected: { backgroundColor: colors.volt },
  choiceTag: { ...typography.action, color: colors.text },
  choiceTagSelected: { color: '#080B0F' },
  choiceTeam: { ...typography.bodyStrong, minHeight: 38, color: colors.text },
  choiceProbability: { ...typography.metricSmall, color: colors.text },
  choiceRisk: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 2 },
  choiceGain: { ...typography.action, color: colors.success },
  choiceSlash: { ...typography.label, marginHorizontal: 2, color: colors.textMuted },
  choiceLoss: { ...typography.action, color: colors.danger },
  choiceFrags: { ...typography.caption, color: colors.textMuted },
  ticket: { padding: spacing.lg, borderRadius: 26, backgroundColor: '#101510', borderWidth: 1, borderColor: '#3A4722', gap: spacing.md },
  ticketTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  ticketEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .9 },
  ticketTeam: { ...typography.cardTitle, marginTop: 5, color: colors.text },
  lockMark: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.volt, alignItems: 'center', justifyContent: 'center' },
  lockMarkText: { color: '#080B0F', fontSize: 14, fontWeight: '900' },
  riskRow: { minHeight: 82, flexDirection: 'row', alignItems: 'stretch', borderRadius: radius.md, backgroundColor: '#0A0E0A', overflow: 'hidden' },
  riskCell: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  riskDivider: { width: 1, marginVertical: 12, backgroundColor: '#303A24' },
  riskLabel: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .7 },
  riskValue: { ...typography.metricSmall, marginTop: 3 },
  riskGain: { color: colors.success },
  riskLoss: { color: colors.danger },
  riskUnitRow: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  riskUnit: { ...typography.caption, color: colors.textMuted },
  ticketHint: { ...typography.body, color: colors.textMuted },
  submitError: { padding: spacing.sm, borderRadius: radius.sm, backgroundColor: '#1A1012', borderWidth: 1, borderColor: '#4A2027', gap: 4 },
  submitErrorTitle: { ...typography.eyebrow, color: '#FF9AA3', letterSpacing: .4 },
  submitErrorCopy: { ...typography.body, color: '#D78891' },
  confirmButton: { minHeight: 54, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.volt, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  confirmPressed: { opacity: .85 },
  confirmText: { ...typography.action, color: '#080B0F', letterSpacing: .4 },
  confirmArrow: { color: '#080B0F', fontSize: 19, fontWeight: '900' },
  webConfirmation: { padding: spacing.md, borderRadius: radius.md, backgroundColor: '#0A0E0A', borderWidth: 1, borderColor: '#4A5B23', gap: spacing.sm },
  webConfirmationTitle: { ...typography.bodyStrong, color: colors.text, letterSpacing: .2 },
  webConfirmationCopy: { ...typography.body, color: colors.textMuted },
  webConfirmationActions: { flexDirection: 'row', gap: spacing.sm },
  webCancelButton: { flex: 1, minHeight: 42, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  webCancelText: { ...typography.action, color: colors.textMuted, letterSpacing: .3 },
  webLockButton: { flex: 1, minHeight: 42, borderRadius: radius.sm, backgroundColor: colors.volt, alignItems: 'center', justifyContent: 'center' },
  webLockText: { ...typography.action, color: '#080B0F', letterSpacing: .3 },
  disabled: { opacity: .5 },
  lockedCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#101510', borderWidth: 1, borderColor: '#3A4722', gap: spacing.md },
  lockedCardWin: { borderColor: '#315D3D', backgroundColor: '#0D1711' },
  lockedCardLoss: { borderColor: '#5A2B32', backgroundColor: '#171012' },
  lockedHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  lockedEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .9 },
  lockedEyebrowLoss: { color: '#FF8C97' },
  lockedTeam: { ...typography.sectionTitle, marginTop: 5, color: colors.text },
  lockedBadge: { minWidth: 46, height: 46, paddingHorizontal: 7, borderRadius: 14, backgroundColor: colors.volt, alignItems: 'center', justifyContent: 'center' },
  lockedBadgeText: { ...typography.action, color: '#080B0F' },
  lockedMeta: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  lockedModel: { ...typography.label, color: colors.textMuted },
  lockedDot: { ...typography.label, color: colors.textMuted },
  verdictLine: { paddingTop: 12, borderTopWidth: 1, borderTopColor: '#303A24', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  verdictLabel: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .7 },
  verdictValue: { ...typography.label, flex: 1, textAlign: 'right', color: colors.text },
  verdictWin: { color: colors.success },
  verdictLoss: { color: colors.danger },
  lockedOutcomeCopy: { ...typography.body, color: colors.textMuted },
  callTimeline: { minHeight: 96, paddingHorizontal: 8, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#090D0A', borderWidth: 1, borderColor: '#2D3720' },
  timelineStep: { flex: 1, minWidth: 0, alignItems: 'center' },
  timelineDot: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#171D18', borderWidth: 1, borderColor: '#303A32' },
  timelineDotComplete: { backgroundColor: colors.volt, borderColor: colors.volt },
  timelineDotText: { ...typography.label, color: colors.textMuted },
  timelineDotTextComplete: { color: '#080B0F' },
  timelineLabel: { ...typography.label, marginTop: 4, color: colors.textMuted, letterSpacing: .25 },
  timelineLabelComplete: { color: colors.text },
  timelineMeta: { ...typography.caption, marginTop: 2, maxWidth: 82, color: '#768179', textAlign: 'center' },
  timelineArrow: { marginHorizontal: -2, color: '#45502B', fontSize: 11, fontWeight: '900' },
  lockedActions: { flexDirection: 'row', gap: spacing.sm },
  lockedPrimaryAction: { flex: 1, minHeight: 46, paddingHorizontal: 10, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.volt },
  lockedPrimaryText: { ...typography.action, color: '#080B0F', letterSpacing: .3, textAlign: 'center' },
  lockedSecondaryAction: { flex: 1, minHeight: 46, paddingHorizontal: 10, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0A0F0B', borderWidth: 1, borderColor: '#3B4725' },
  lockedSecondaryText: { ...typography.action, color: colors.volt, letterSpacing: .3, textAlign: 'center' },
  duelAction: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#11170E', borderWidth: 1, borderColor: '#414D1E', gap: spacing.md },
  duelActionCopy: { gap: 6 },
  duelActionEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .9 },
  duelActionTitle: { ...typography.cardTitle, color: colors.text },
  duelActionText: { ...typography.body, color: colors.textMuted },
  duelActionError: { ...typography.body, color: '#FF9AA3' },
  duelActionButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.volt },
  duelActionButtonText: { ...typography.action, color: '#080B0F', letterSpacing: .4 },
  closedCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 8 },
  closedEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: 1 },
  closedTitle: { ...typography.cardTitle, color: colors.text },
  closedCopy: { ...typography.body, color: colors.textMuted },
  infoCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#090D11', borderWidth: 1, borderColor: colors.border, gap: 7 },
  infoEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .9 },
  infoTitle: { ...typography.cardTitle, color: colors.text },
  infoCopy: { ...typography.body, color: colors.textMuted },
  relatedSection: { gap: 12 },
  relatedEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .9 },
  relatedTitle: { ...typography.sectionTitle, marginTop: 4, color: colors.text },
  relatedRail: { gap: spacing.sm },
  relatedCard: { width: 224, minHeight: 166, padding: 14, borderRadius: 18, backgroundColor: '#0A0F14', borderWidth: 1, borderColor: colors.border },
  relatedTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  relatedWhen: { ...typography.label, color: colors.volt, letterSpacing: .25 },
  relatedGame: { ...typography.label, color: colors.textMuted },
  relatedEvent: { ...typography.caption, marginTop: 10, color: colors.textMuted },
  relatedDuel: { ...typography.metricSmall, marginTop: 10, color: colors.text },
  relatedVs: { ...typography.label, color: colors.textMuted },
  relatedFooter: { marginTop: 'auto', paddingTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#1D252D' },
  relatedFormat: { ...typography.label, color: colors.textMuted, letterSpacing: .35 },
  relatedArrow: { color: colors.volt, fontSize: 16, fontWeight: '900' },
  errorCard: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#1A1012', borderWidth: 1, borderColor: '#48242A', gap: 8 },
  errorTitle: { ...typography.cardTitle, color: colors.text },
  errorCopy: { ...typography.body, color: '#FF9AA3' },
  retry: { ...typography.action, color: colors.volt, letterSpacing: .5 },
  loadingCard: { height: 290, padding: spacing.lg, borderRadius: 30, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 12 },
  loadingLineWide: { width: '65%', height: 10, borderRadius: 5, backgroundColor: colors.surfaceElevated },
  loadingLine: { width: '38%', height: 8, borderRadius: 4, backgroundColor: colors.surfaceElevated },
  loadingDuel: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  loadingCircle: { width: 72, height: 72, borderRadius: 24, backgroundColor: colors.surfaceElevated },
  pressed: { opacity: .82, transform: [{ scale: .99 }] },
});
