import { StyleSheet } from 'react-native';

import { colors, fonts, layout, spacing, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  gameBackground: { position: 'absolute', inset: 0, overflow: 'hidden', backgroundColor: '#020609' },
  gameBackgroundImage: { position: 'absolute', inset: 0, width: '100%', height: '100%' },
  gameBackgroundScrim: { position: 'absolute', inset: 0 },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingBottom: layout.tabBarContentInset, gap: 14 },
  targetedDuelBanner: { minHeight: 84, marginHorizontal: spacing.md, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, backgroundColor: 'rgba(18,25,11,.76)', borderWidth: 1, borderColor: '#4A5720' }, targetedDuelCopy: { flex: 1, minWidth: 0 }, targetedDuelEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: .75 }, targetedDuelTitle: { ...typography.bodyStrong, marginTop: 5, color: colors.text }, targetedDuelClose: { width: layout.minTouchTarget, height: layout.minTouchTarget, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(8,13,7,.74)', borderWidth: 1, borderColor: '#35401B' }, targetedDuelCloseText: { color: colors.textMuted, fontSize: 23, lineHeight: 24 },
  scheduleHero: { minHeight: 142, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: 'rgba(105,130,145,.3)', gap: 14 },
  scheduleHeroLandscape: { minHeight: 126 },
  scheduleHeroLive: { minHeight: 50, paddingBottom: 6 },
  scheduleTop: { zIndex: 2, minHeight: layout.minTouchTarget, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  scheduleActions: { flexDirection: 'row', gap: 6 },
  iconButton: { width: layout.minTouchTarget, height: layout.minTouchTarget, alignItems: 'center', justifyContent: 'center' },
  scheduleMonth: { fontFamily: fonts.medium, fontSize: 16, lineHeight: 22, color: colors.text, flex: 1 },
  daysScroll: { flexGrow: 0, flexShrink: 0 },
  daysRow: { minWidth: '100%', flexGrow: 1, flexDirection: 'row', justifyContent: 'space-between', gap: 3 },
  dayButton: { flex: 1, width: layout.minTouchTarget, minWidth: layout.minTouchTarget, height: 58, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  dayButtonLandscape: { height: layout.minTouchTarget, borderRadius: 15 },
  dayButtonActive: { backgroundColor: '#F5F6F0', borderColor: '#FFFFFF' },
  dayButtonPressed: { transform: [{ scale: .96 }] },
  dayName: { fontFamily: fonts.medium, fontSize: 10, lineHeight: 14, color: colors.textMuted },
  dayNumber: { fontFamily: fonts.bold, fontSize: 19, lineHeight: 25, marginTop: 3, color: colors.text },
  dayTextActive: { color: '#0A0E11' },
  dayMatchDot: { width: 4, height: 4, marginTop: 1, borderRadius: 2, backgroundColor: 'transparent' },
  dayMatchDotVisible: { backgroundColor: colors.volt },
  dayMatchDotActive: { backgroundColor: '#0A0E11' },
  stateInset: { marginHorizontal: spacing.md },
  matchesSection: { marginHorizontal: spacing.md, gap: 12 },
  sectionHead: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  sectionEyebrow: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: 1.1 },
  sectionTitle: { ...typography.sectionTitle, marginTop: 4, color: colors.text },
  countPill: { minHeight: 27, paddingHorizontal: 10, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(10,16,22,.68)', borderWidth: 1, borderColor: '#29323B' },
  countText: { ...typography.label, color: colors.textSubtle, letterSpacing: .4 },
  liveStack: { gap: 10 },
  liveCard: { minHeight: 240, overflow: 'hidden', borderRadius: 26, backgroundColor: 'rgba(7,14,20,.68)', borderWidth: 1, borderColor: 'rgba(121,150,171,.42)', padding: 15 },
  liveTop: { zIndex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  liveEvent: { ...typography.label, flex: 1, color: 'rgba(255,255,255,.76)', letterSpacing: .35 },
  livePill: { minHeight: 28, paddingHorizontal: 10, borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.liveSurface, borderWidth: 1, borderColor: colors.liveBorder },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.live },
  liveText: { ...typography.eyebrow, color: colors.liveText, letterSpacing: .7 },
  liveDuel: { zIndex: 2, marginTop: 25, flexDirection: 'row', alignItems: 'flex-start', gap: 16 },
  matchTeam: { flex: 1, minWidth: 0, alignItems: 'center', gap: 7 },
  matchTeamName: { ...typography.bodyStrong, width: '100%', minHeight: 36, color: '#FFFFFF', textAlign: 'center', fontSize: 14, lineHeight: 18 },
  matchTeamNameCompact: { minHeight: 32, fontSize: 12, lineHeight: 16 },
  liveScore: { minWidth: 66, flexShrink: 0, alignItems: 'center' },
  liveBo: { ...typography.eyebrow, color: 'rgba(255,255,255,.58)', letterSpacing: .7 },
  liveScoreText: { ...typography.displayMedium, marginTop: 5, color: '#FFFFFF' },
  liveFooter: { zIndex: 2, minHeight: 38, marginTop: 'auto', paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.13)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  liveFooterText: { ...typography.action, color: '#D5DBDF', letterSpacing: .7 },
  liveFooterCall: { color: colors.volt },
  liveFooterArrow: { color: colors.volt, fontSize: 17 },
  matchList: { overflow: 'hidden', borderRadius: 20, backgroundColor: 'rgba(7,13,18,.72)', borderWidth: 1, borderColor: 'rgba(97,119,136,.30)' },
  matchRow: { minHeight: 140, padding: 11, gap: 10, borderBottomWidth: 1, borderBottomColor: '#192129' },
  rowHeader: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  rowWhen: { width: 43 },
  rowTime: { ...typography.bodyStrong, color: '#F3F6F7' },
  rowGame: { ...typography.caption, marginTop: 3, color: colors.textMuted },
  rowEvent: { ...typography.caption, flex: 1, minWidth: 0, color: colors.textMuted },
  rowDuel: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  rowScore: { minWidth: 56, minHeight: 42, alignItems: 'center', justifyContent: 'center' },
  rowTeams: { ...typography.bodyStrong, color: colors.text },
  rowTrailing: { minWidth: 58, alignItems: 'flex-end', gap: 2 },
  rowState: { ...typography.label, color: colors.textMuted, letterSpacing: .15 },
  rowStateAccent: { color: colors.volt },
  rowStateLoss: { color: colors.danger },
  rowArrow: { color: colors.volt, fontSize: 16 },
  skeleton: { marginHorizontal: spacing.md, gap: 10 },
  skeletonHead: { minHeight: 43, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  skeletonHeadCopy: { flex: 1, gap: 6 },
  skeletonList: { overflow: 'hidden', borderRadius: 20, backgroundColor: 'rgba(7,13,18,.72)', borderWidth: 1, borderColor: 'rgba(97,119,136,.30)' },
  skeletonRow: { minHeight: 98, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 9 },
  skeletonRowDivider: { borderTopWidth: 1, borderTopColor: '#192129' },
  skeletonWhen: { width: 43, gap: 6 },
  skeletonLogos: { width: 52, flexDirection: 'row', alignItems: 'center' },
  skeletonLogoOverlap: { marginLeft: -15 },
  skeletonRowCopy: { flex: 1, minWidth: 0, gap: 8 },
  pressed: { opacity: .76 },
});
