import type { ShowcaseRingAssets, ShowcaseRingFamily, ShowcaseRingStage } from './types';

type StageAssetMap = Record<ShowcaseRingStage, ShowcaseRingAssets>;

export const SHOWCASE_RING_ASSETS: Record<ShowcaseRingFamily, StageAssetMap> = {
  rank: stages(
    require('../../../../assets/showcase/evolution-badges/badge-elite-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-elite-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-elite-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-elite-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-elite-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-elite-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-elite-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-elite-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-elite-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-elite-05-thumb.webp'),
  ),
  streak: stages(
    require('../../../../assets/showcase/evolution-badges/badge-trace-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-trace-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-trace-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-trace-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-trace-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-trace-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-trace-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-trace-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-trace-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-trace-05-thumb.webp'),
  ),
  faction: stages(
    require('../../../../assets/showcase/evolution-badges/badge-cercle-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-cercle-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-cercle-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-cercle-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-cercle-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-cercle-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-cercle-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-cercle-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-cercle-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-cercle-05-thumb.webp'),
  ),
  major: stages(
    require('../../../../assets/showcase/evolution-badges/badge-regard-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-regard-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-regard-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-regard-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-regard-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-regard-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-regard-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-regard-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-regard-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-regard-05-thumb.webp'),
  ),
  seniority: stages(
    require('../../../../assets/showcase/evolution-badges/badge-heritage-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-heritage-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-heritage-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-heritage-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-heritage-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-heritage-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-heritage-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-heritage-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-heritage-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-heritage-05-thumb.webp'),
  ),
  ritual: stages(
    require('../../../../assets/showcase/evolution-badges/badge-ritual-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ritual-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ritual-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ritual-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ritual-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ritual-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ritual-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ritual-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ritual-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ritual-05-thumb.webp'),
  ),
  countercurrent: stages(
    require('../../../../assets/showcase/evolution-badges/badge-countercurrent-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-countercurrent-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-countercurrent-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-countercurrent-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-countercurrent-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-countercurrent-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-countercurrent-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-countercurrent-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-countercurrent-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-countercurrent-05-thumb.webp'),
  ),
  clean_sweep: stages(
    require('../../../../assets/showcase/evolution-badges/badge-clean-sweep-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-clean-sweep-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-clean-sweep-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-clean-sweep-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-clean-sweep-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-clean-sweep-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-clean-sweep-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-clean-sweep-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-clean-sweep-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-clean-sweep-05-thumb.webp'),
  ),
  ascension: stages(
    require('../../../../assets/showcase/evolution-badges/badge-ascension-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ascension-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ascension-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ascension-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-ascension-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ascension-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ascension-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ascension-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ascension-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-ascension-05-thumb.webp'),
  ),
  duelist: stages(
    require('../../../../assets/showcase/evolution-badges/badge-duelist-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-duelist-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-duelist-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-duelist-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-duelist-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-duelist-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-duelist-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-duelist-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-duelist-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-duelist-05-thumb.webp'),
  ),
  pact: stages(
    require('../../../../assets/showcase/evolution-badges/badge-pact-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-pact-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-pact-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-pact-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-pact-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-pact-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-pact-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-pact-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-pact-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-pact-05-thumb.webp'),
  ),
  echo: stages(
    require('../../../../assets/showcase/evolution-badges/badge-echo-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-echo-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-echo-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-echo-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-echo-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-echo-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-echo-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-echo-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-echo-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-echo-05-thumb.webp'),
  ),
  metamorphosis: stages(
    require('../../../../assets/showcase/evolution-badges/badge-metamorphosis-01.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-metamorphosis-02.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-metamorphosis-03.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-metamorphosis-04.webp'),
    require('../../../../assets/showcase/evolution-badges/badge-metamorphosis-05.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-metamorphosis-01-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-metamorphosis-02-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-metamorphosis-03-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-metamorphosis-04-thumb.webp'),
    require('../../../../assets/showcase/evolution-badges/thumbs/badge-metamorphosis-05-thumb.webp'),
  ),
};

function stages(
  full1: ShowcaseRingAssets['full'],
  full2: ShowcaseRingAssets['full'],
  full3: ShowcaseRingAssets['full'],
  full4: ShowcaseRingAssets['full'],
  full5: ShowcaseRingAssets['full'],
  thumbnail1: ShowcaseRingAssets['thumbnail'],
  thumbnail2: ShowcaseRingAssets['thumbnail'],
  thumbnail3: ShowcaseRingAssets['thumbnail'],
  thumbnail4: ShowcaseRingAssets['thumbnail'],
  thumbnail5: ShowcaseRingAssets['thumbnail'],
): StageAssetMap {
  return {
    1: { full: full1, thumbnail: thumbnail1 },
    2: { full: full2, thumbnail: thumbnail2 },
    3: { full: full3, thumbnail: thumbnail3 },
    4: { full: full4, thumbnail: thumbnail4 },
    5: { full: full5, thumbnail: thumbnail5 },
  };
}
