import { StyleSheet } from 'react-native';

import { colors, fonts, layout, radius, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingHorizontal: 18, paddingTop: 6, paddingBottom: layout.tabBarContentInset + 12, gap: 10 },
  error: { minHeight: 48, padding: 12, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, backgroundColor: '#1A1012', borderWidth: 1, borderColor: '#4A2027' },
  errorText: { ...typography.body, flex: 1, color: '#FF9AA2' },
  retry: { ...typography.action, color: colors.volt },
  factionHero: { position: 'relative', minHeight: 544, overflow: 'hidden', padding: 12, borderRadius: 22, backgroundColor: '#06111A', borderWidth: 1, borderColor: '#284553', boxShadow: '0 0 24px rgba(22,80,105,.1)' },
  heroAura: { position: 'absolute', width: 340, height: 340, left: 28, top: 58, borderRadius: 170, backgroundColor: 'rgba(160,92,50,.07)', boxShadow: '0 0 86px rgba(169,91,45,.09)' },
  heroAuraCold: { position: 'absolute', width: 350, height: 380, left: -76, top: 72, borderRadius: 190, backgroundColor: 'rgba(23,123,145,.09)', boxShadow: '0 0 90px rgba(32,140,162,.12)' },
  heroGridLineA: { position: 'absolute', width: 520, height: 1, left: -62, top: 220, backgroundColor: 'rgba(188,112,67,.13)', transform: [{ rotate: '16deg' }] },
  heroGridLineB: { position: 'absolute', width: 520, height: 1, left: -62, top: 282, backgroundColor: 'rgba(50,153,169,.11)', transform: [{ rotate: '-14deg' }] },
  heroTop: { zIndex: 6, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  heroHeading: { flex: 1, minWidth: 0 },
  heroEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: 1.1 },
  heroTitle: { ...typography.displayMedium, maxWidth: 205, marginTop: 4, color: '#F4F3EF' },
  levelPill: { flexShrink: 0, minHeight: 27, paddingHorizontal: 9, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(5,10,14,.82)', borderWidth: 1, borderColor: '#30414B' },
  levelDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.volt },
  levelText: { ...typography.label, color: '#D6DCE0', letterSpacing: .35 },
  relicQuestion: { color: colors.volt, fontFamily: fonts.display, fontSize: 22 },
  factionIdentity: { zIndex: 4, minHeight: 46, marginTop: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  factionSeal: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#060A0D', borderWidth: 1, borderColor: '#687A2B' },
  factionIdentityCopy: { flex: 1, minWidth: 0 },
  factionName: { ...typography.bodyStrong, color: '#F6F7F5', letterSpacing: .1 },
  factionMeta: { ...typography.caption, marginTop: 3, color: '#86939D' },
  factionGrowthBlock: { flexShrink: 0, flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  factionGrowth: { ...typography.metricSmall, color: colors.volt },
  factionGrowthLabel: { ...typography.eyebrow, color: colors.textMuted, letterSpacing: .2 },
  supporterArrivalOverlay: { position: 'absolute', zIndex: 5, top: 0, right: 0, bottom: 0, left: 0, overflow: 'visible' },
  progressBlock: { zIndex: 4, marginTop: 8 },
  relicForm: { ...typography.eyebrow, color: colors.volt, letterSpacing: .7 },
  progressHeadline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressValue: { ...typography.label, color: '#F4F6F2' },
  progressTrack: { height: 4, marginTop: 6, overflow: 'hidden', borderRadius: 3, backgroundColor: '#172029' },
  progressFill: { height: '100%', minWidth: 4, borderRadius: 3, backgroundColor: colors.volt, boxShadow: '0 0 9px rgba(232,255,61,.5)' },
  progressFoot: { minHeight: 14, marginTop: 6 },
  progressNext: { ...typography.caption, color: colors.textMuted },
  rallyButton: { minHeight: 44, marginTop: 5, padding: 2, overflow: 'hidden', borderRadius: 10, backgroundColor: '#69760E', borderWidth: 1, borderColor: '#C8DC21', boxShadow: '0 0 17px rgba(232,255,61,.2)' },
  rallySurface: { flex: 1, width: '100%', minHeight: 38, overflow: 'hidden', borderRadius: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, paddingHorizontal: 11 },
  rallyFacet: { position: 'absolute', width: 42, height: 62, backgroundColor: 'rgba(255,255,255,.1)', transform: [{ rotate: '24deg' }] },
  rallyFacetLeft: { left: -22, top: -18 },
  rallyFacetRight: { right: -28, bottom: -22 },
  rallyIcon: { width: 29, height: 29, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#11180D', borderWidth: 1, borderColor: 'rgba(7,10,8,.82)' },
  supporterGlyph: { position: 'relative', width: 19, height: 17 },
  supporterHead: { position: 'absolute', width: 5, height: 5, borderRadius: 3, backgroundColor: colors.volt },
  supporterHeadLeft: { left: 0, top: 5 },
  supporterHeadCenter: { left: 7, top: 1 },
  supporterHeadRight: { right: 0, top: 5 },
  supporterShoulder: { position: 'absolute', height: 7, borderWidth: 1.5, borderBottomWidth: 0, borderColor: colors.volt, borderTopLeftRadius: 6, borderTopRightRadius: 6 },
  supporterShoulderLeft: { width: 8, left: 0, bottom: 0 },
  supporterShoulderCenter: { width: 10, left: 4.5, bottom: 2 },
  supporterShoulderRight: { width: 8, right: 0, bottom: 0 },
  rallyText: { ...typography.cardTitle, flexShrink: 1, color: '#090C0E', fontSize: 14, lineHeight: 18, letterSpacing: .16, textAlign: 'center' },
  warSection: { padding: 7, gap: 3, borderRadius: 20, backgroundColor: '#091017', borderWidth: 1, borderColor: '#263640' },
  sectionHeading: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  sectionHeadingCopy: { flex: 1, minWidth: 0 },
  sectionEyebrow: { ...typography.eyebrow, color: colors.volt },
  sectionTitle: { ...typography.cardTitle, marginTop: 2, color: '#F3F5F5', fontSize: 15, lineHeight: 18 },
  livePill: { minHeight: 25, paddingHorizontal: 8, borderRadius: 13, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#11170E', borderWidth: 1, borderColor: '#3B471D' },
  liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: colors.volt },
  liveText: { ...typography.label, color: colors.volt, letterSpacing: .35 },
  warCard: { overflow: 'hidden', borderRadius: 14, backgroundColor: '#080D12', borderWidth: 1, borderColor: '#303A31' },
  warRow: { minHeight: 42, paddingHorizontal: 6, flexDirection: 'row', alignItems: 'center', gap: 5, borderBottomWidth: 1, borderBottomColor: '#1D262D' },
  warRowMine: { backgroundColor: '#151B10', borderBottomColor: '#3A451C' },
  warRankBadge: { width: 24, height: 25, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0D1318', borderWidth: 1, borderColor: '#34404A' },
  warRankBadgeFirst: { backgroundColor: '#1B220F', borderColor: '#66752C' },
  warRank: { ...typography.metricSmall, color: '#7A8791' },
  warRankFirst: { color: colors.volt },
  warTeam: { flex: 1, minWidth: 0 },
  warNameLine: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  warName: { ...typography.bodyStrong, flexShrink: 1, color: '#F0F2F3' },
  minePill: { flexShrink: 0, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 6, backgroundColor: colors.volt },
  minePillText: { ...typography.label, color: '#080A0C', fontSize: 8, lineHeight: 10, letterSpacing: .1 },
  warMeta: { ...typography.caption, marginTop: 3, color: colors.textMuted },
  warScore: { minWidth: 54, alignItems: 'flex-end' },
  warMembers: { ...typography.metricSmall, color: '#F0F2F3' },
  warMemberLabel: { ...typography.label, marginTop: -1, color: '#99A5AE', fontSize: 7, lineHeight: 9, letterSpacing: .25 },
  warGrowth: { ...typography.label, marginTop: 2, color: colors.textMuted, fontSize: 8, lineHeight: 10 },
  warGrowthPositive: { color: colors.volt },
  warGrowthNegative: { color: colors.danger },
  memberSection: { gap: 11 },
  memberPlacement: { ...typography.eyebrow, color: colors.volt, letterSpacing: .4 },
  memberSummary: { minHeight: 118, padding: 13, borderRadius: 24, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#10160E', borderWidth: 1, borderColor: '#3C481D' },
  memberRankBlock: { minWidth: 68 },
  memberRankValue: { ...typography.metric, color: colors.volt },
  memberRankLabel: { ...typography.label, marginTop: 4, color: colors.textMuted, letterSpacing: .35 },
  memberDivider: { width: 1, height: 56, backgroundColor: '#38431D' },
  memberStat: { flex: 1, minWidth: 0, alignItems: 'center' },
  memberStatValue: { ...typography.metricSmall, color: '#F1F3F2' },
  memberStatValueFeatured: { color: colors.volt },
  memberStatLabel: { ...typography.label, marginTop: 4, color: colors.textMuted, textAlign: 'center' },
  memberList: { overflow: 'hidden', borderRadius: 22, backgroundColor: '#0A0F14', borderWidth: 1, borderColor: '#242D35' },
  memberRow: { minHeight: 78, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: '#192129' },
  memberRowMine: { backgroundColor: '#141B10' },
  memberRowRank: { ...typography.label, width: 27, color: '#8C98A2' },
  memberRowRankMine: { color: colors.volt },
  memberAvatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#171E0E', borderWidth: 1, borderColor: '#38431D' },
  memberAvatarText: { ...typography.label, color: colors.volt },
  memberCopy: { flex: 1, minWidth: 0 },
  memberName: { ...typography.bodyStrong, color: '#F0F2F3' },
  memberMeta: { ...typography.caption, marginTop: 3, color: colors.textMuted },
  memberPrecision: { ...typography.label, color: '#AAB3B9' },
  emptyCard: { minHeight: 190, padding: 22, borderRadius: 28, justifyContent: 'center', backgroundColor: '#0A0F14', borderWidth: 1, borderColor: '#252E36' },
  emptyMark: { color: colors.volt, fontSize: 24 },
  emptyTitle: { ...typography.displaySmall, maxWidth: 320, marginTop: 12, color: '#F2F4F4' },
  emptyText: { ...typography.body, maxWidth: 330, marginTop: 9, color: '#7A858E' },
  heroSkeleton: { minHeight: 600, padding: 18, borderRadius: 27, justifyContent: 'space-between', backgroundColor: '#09131A', borderWidth: 1, borderColor: '#263844' },
  skeletonTitle: { width: 220, height: 65, borderRadius: 17, backgroundColor: '#172016' },
  skeletonRelic: { width: 230, height: 230, alignSelf: 'center', borderRadius: 115, backgroundColor: '#151C18' },
  skeletonLine: { width: '100%', height: 58, borderRadius: 16, backgroundColor: '#151C18' },
  pressed: { opacity: .74 },
});
