import { StyleSheet } from 'react-native';

import { colors, fonts, layout, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: 'transparent' },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingHorizontal: 18, paddingTop: 6, paddingBottom: layout.tabBarContentInset + 12, gap: 10 },
  factionHero: { position: 'relative', minHeight: 544, overflow: 'hidden', padding: 12, borderRadius: 22, backgroundColor: 'rgba(6,24,35,.88)', borderWidth: 1, borderColor: colors.borderHighlight },
  heroTop: { zIndex: 6, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  heroHeading: { flex: 1, minWidth: 0 },
  heroEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: 1.1 },
  heroTitle: { ...typography.displayMedium, maxWidth: 205, marginTop: 4, color: '#F4F3EF' },
  levelPill: { flexShrink: 0, minHeight: 27, paddingHorizontal: 9, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(5,10,14,.82)', borderWidth: 1, borderColor: '#30414E' },
  levelDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.volt },
  levelText: { ...typography.label, color: '#D6DCE0', letterSpacing: .35 },
  relicQuestion: { color: colors.volt, fontFamily: fonts.display, fontSize: 22 },
  factionIdentity: { zIndex: 4, minHeight: 46, marginTop: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  factionSeal: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#687A2B' },
  factionIdentityCopy: { flex: 1, minWidth: 0 },
  factionName: { ...typography.bodyStrong, color: '#F6F7F5', letterSpacing: .1 },
  factionMeta: { ...typography.caption, marginTop: 3, color: '#9AA5AE' },
  factionGrowthBlock: { flexShrink: 0, flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  factionGrowth: { ...typography.metricSmall, color: colors.volt },
  factionGrowthLabel: { ...typography.eyebrow, color: '#9AA5AE', letterSpacing: .2 },
  progressBlock: { zIndex: 4, marginTop: 8 },
  relicForm: { ...typography.eyebrow, color: colors.volt, letterSpacing: .7 },
  progressHeadline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressValue: { ...typography.label, color: '#F4F6F2' },
  progressTrack: { height: 4, marginTop: 6, overflow: 'hidden', borderRadius: 3, backgroundColor: '#172029' },
  progressFill: { height: '100%', minWidth: 4, borderRadius: 3, backgroundColor: colors.volt },
  progressFoot: { minHeight: 14, marginTop: 6 },
  progressNext: { ...typography.caption, color: '#98A3AC' },
  rallyButton: { minHeight: 44, marginTop: 5, overflow: 'hidden', borderRadius: 12, backgroundColor: '#0F1510', borderWidth: 1, borderColor: '#58651E' },
  rallySurface: { flex: 1, width: '100%', minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, paddingHorizontal: 12 },
  rallyIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  supporterGlyph: { position: 'relative', width: 19, height: 17 },
  supporterHead: { position: 'absolute', width: 5, height: 5, borderRadius: 3, backgroundColor: colors.volt },
  supporterHeadLeft: { left: 0, top: 5 },
  supporterHeadCenter: { left: 7, top: 1 },
  supporterHeadRight: { right: 0, top: 5 },
  supporterShoulder: { position: 'absolute', height: 7, borderWidth: 1.5, borderBottomWidth: 0, borderColor: colors.volt, borderTopLeftRadius: 6, borderTopRightRadius: 6 },
  supporterShoulderLeft: { width: 8, left: 0, bottom: 0 },
  supporterShoulderCenter: { width: 10, left: 4.5, bottom: 2 },
  supporterShoulderRight: { width: 8, right: 0, bottom: 0 },
  rallyText: { ...typography.cardTitle, flexShrink: 1, color: colors.volt, fontSize: 14, lineHeight: 18, letterSpacing: .16, textAlign: 'center' },
  warSection: { marginTop: 20, gap: 11 },
  warSectionHeading: { alignItems: 'center', paddingHorizontal: 5 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  sectionEyebrow: { color: colors.volt, fontFamily: fonts.bold, fontSize: 11, lineHeight: 14, letterSpacing: .8 },
  sectionTitle: { marginTop: 5, color: '#F3F5F5', fontFamily: fonts.display, fontSize: 27, lineHeight: 29, letterSpacing: -.25 },
  warSectionTitle: { flex: 1, minWidth: 0, color: '#F4F5F3', fontFamily: fonts.display, fontSize: 20, lineHeight: 22, letterSpacing: .5 },
  warSectionTitleCompact: { fontSize: 17, lineHeight: 19, letterSpacing: .2 },
  warPeriod: { minHeight: 30, flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 11, borderRadius: 16, backgroundColor: 'rgba(7,16,23,.86)', borderWidth: 1, borderColor: '#334655' },
  warPeriodDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.volt, boxShadow: '0 0 8px rgba(232,255,61,.5)' },
  warPeriodText: { color: '#F1F3EF', fontFamily: fonts.displayBold, fontSize: 14, lineHeight: 17, letterSpacing: .8 },
  warBoard: { gap: 7 },
  factionLeaderCard: { position: 'relative', minHeight: 190, overflow: 'hidden', padding: 13, flexDirection: 'row', alignItems: 'stretch', borderRadius: 18, borderWidth: 1, boxShadow: '0 14px 26px rgba(0,0,0,.32)' },
  factionLeaderCardCompact: { minHeight: 174, padding: 10 },
  factionLeaderBeam: { position: 'absolute', left: -54, top: 75, width: 238, height: 42, opacity: .08, transform: [{ rotate: '-34deg' }] },
  factionLeaderBeamSecondary: { left: -18, top: 122, width: 192, height: 30, opacity: .06 },
  factionLeaderVisual: { position: 'relative', flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center' },
  factionLeaderRank: { position: 'absolute', zIndex: 2, top: 2, left: 0, color: '#F6F7F7', fontFamily: fonts.display, fontSize: 39, lineHeight: 40, letterSpacing: -.7 },
  factionLeaderRankCompact: { fontSize: 34, lineHeight: 35 },
  factionRankingArtworkBlend: { overflow: 'hidden', borderRadius: 16, mixBlendMode: 'screen' },
  factionRankingArtwork: { width: '100%', height: '100%' },
  factionLeaderInfo: { width: '45%', minWidth: 118, justifyContent: 'center', paddingLeft: 5 },
  factionLeaderInfoCompact: { width: '46%', minWidth: 108, paddingLeft: 2 },
  factionLeaderName: { color: '#F6F7F7', fontFamily: fonts.display, fontSize: 25, lineHeight: 27, letterSpacing: .2 },
  factionLeaderNameCompact: { fontSize: 21, lineHeight: 23 },
  factionLeaderMetaRow: { minHeight: 18, marginTop: 3, flexDirection: 'row', alignItems: 'center', gap: 6 },
  factionLeaderTag: { color: '#9DA8B2', fontFamily: fonts.displayBold, fontSize: 12, lineHeight: 15, letterSpacing: .9 },
  factionLeaderBullet: { color: '#8E99A4', fontFamily: fonts.bold, fontSize: 10 },
  factionLeaderMine: { flexShrink: 1, color: colors.volt, fontFamily: fonts.displayBold, fontSize: 12, lineHeight: 15, letterSpacing: .65 },
  factionRankingDivider: { height: 1, marginVertical: 7, backgroundColor: 'rgba(185,201,212,.22)' },
  factionLeaderSupporters: { color: '#F7F7F5', fontFamily: fonts.display, fontSize: 33, lineHeight: 34, letterSpacing: .35 },
  factionLeaderSupportersCompact: { fontSize: 29, lineHeight: 30 },
  factionLeaderSupporterLabel: { marginTop: 1, color: '#A1A9B0', fontFamily: fonts.displayBold, fontSize: 11, lineHeight: 13, letterSpacing: 1 },
  factionLeaderGrowth: { color: colors.volt, fontFamily: fonts.displayBold, fontSize: 15, lineHeight: 17, letterSpacing: .7 },
  factionLeaderGrowthPeriod: { color: '#9DA5AE' },
  factionPodiumRow: { position: 'relative', minHeight: 86, overflow: 'hidden', paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 16, borderWidth: 1, boxShadow: '0 9px 18px rgba(0,0,0,.22)' },
  factionPodiumRowCompact: { minHeight: 78, paddingHorizontal: 8, gap: 4 },
  factionPodiumGlow: { position: 'absolute', top: -40, left: -34, width: 172, height: 172, borderRadius: 86, opacity: .07 },
  factionPodiumRank: { width: 41, color: '#F5F6F6', fontFamily: fonts.display, fontSize: 31, lineHeight: 33, letterSpacing: -.55 },
  factionPodiumRankCompact: { width: 34, fontSize: 27, lineHeight: 29 },
  factionPodiumLogo: { width: 72, height: 72, flexShrink: 0, alignItems: 'center', justifyContent: 'center' },
  factionPodiumLogoCompact: { width: 58, height: 62 },
  factionPodiumIdentity: { flex: 1, minWidth: 0 },
  factionPodiumName: { color: '#F5F6F5', fontFamily: fonts.display, fontSize: 21, lineHeight: 23, letterSpacing: .25 },
  factionPodiumNameCompact: { fontSize: 18, lineHeight: 20 },
  factionPodiumMetaRow: { marginTop: 3, flexDirection: 'row', alignItems: 'center', gap: 5 },
  factionPodiumTag: { color: '#9AA3AC', fontFamily: fonts.displayBold, fontSize: 11, lineHeight: 13, letterSpacing: .9 },
  factionPodiumMine: { color: colors.volt, fontFamily: fonts.displayBold, fontSize: 9, lineHeight: 12, letterSpacing: .5 },
  factionPodiumMetrics: { width: 78, flexShrink: 0, alignItems: 'flex-start' },
  factionPodiumMetricsCompact: { width: 68 },
  factionPodiumSupporters: { color: '#F5F6F5', fontFamily: fonts.display, fontSize: 24, lineHeight: 25, letterSpacing: .2 },
  factionPodiumSupportersCompact: { fontSize: 21, lineHeight: 22 },
  factionPodiumSupporterLabel: { marginTop: 1, color: '#9CA4AB', fontFamily: fonts.displayBold, fontSize: 8, lineHeight: 10, letterSpacing: .75 },
  factionPodiumDivider: { width: '100%', height: 1, marginVertical: 5, backgroundColor: 'rgba(185,201,212,.20)' },
  factionPodiumGrowth: { color: colors.volt, fontFamily: fonts.displayBold, fontSize: 11, lineHeight: 13, letterSpacing: .45 },
  factionPodiumPeriod: { color: '#9BA4AC', fontSize: 9 },
  memberSection: { marginTop: 18, gap: 9 },
  memberHeading: { paddingHorizontal: 5 },
  memberIdentityCard: { position: 'relative', minHeight: 102, overflow: 'hidden', borderRadius: 16, borderWidth: 1, boxShadow: '0 10px 20px rgba(0,0,0,.24)' },
  memberIdentityGlow: { position: 'absolute', top: -74, left: -52, width: 190, height: 190, borderRadius: 95, opacity: .08 },
  memberIdentityBody: { minHeight: 102, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 11 },
  memberIdentityBodyCompact: { minHeight: 94, padding: 8, gap: 8 },
  memberStatsPanel: { overflow: 'hidden', borderRadius: 16, borderWidth: 1, borderColor: '#30414E', boxShadow: '0 10px 20px rgba(0,0,0,.2)' },
  memberStats: { minHeight: 72, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center' },
  memberStat: { flex: 1, minWidth: 0, minHeight: 66, alignItems: 'center', justifyContent: 'center' },
  memberStatDivider: { width: 1, height: 42, backgroundColor: '#33414B' },
  memberStatValue: { color: '#F1F3F2', fontFamily: fonts.display, fontSize: 28, lineHeight: 29 },
  memberStatValueFeatured: { color: colors.volt },
  memberStatLabel: { marginTop: 4, color: '#8E989D', fontFamily: fonts.displayBold, fontSize: 10, lineHeight: 12, letterSpacing: .85, textAlign: 'center' },
  memberAvatar: { width: 78, height: 78, overflow: 'hidden', flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 39, backgroundColor: '#06121D', borderWidth: 1.5, borderColor: colors.volt, boxShadow: '0 0 13px rgba(232,255,61,.15)' },
  memberAvatarCompact: { width: 66, height: 66, borderRadius: 33 },
  memberRankingBody: { flex: 1, minWidth: 0, gap: 7 },
  memberRankingHeadline: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  memberCopy: { flex: 1, minWidth: 0 },
  memberName: { color: '#F0F2F3', fontFamily: fonts.bold, fontSize: 16, lineHeight: 20 },
  memberNameCompact: { fontSize: 13, lineHeight: 17 },
  memberMeta: { marginTop: 2, color: colors.volt, fontFamily: fonts.displayBold, fontSize: 11, lineHeight: 13, letterSpacing: .8 },
  memberRankGroup: { flexShrink: 0, flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  memberRankPrimary: { color: colors.volt, fontFamily: fonts.display, fontSize: 29, lineHeight: 30, letterSpacing: -.25 },
  memberRankPrimaryCompact: { fontSize: 25, lineHeight: 26 },
  memberRankTotal: { color: '#8F98A5', fontFamily: fonts.displayBold, fontSize: 16, lineHeight: 19, letterSpacing: .25 },
  memberRankTotalCompact: { fontSize: 13, lineHeight: 16 },
  memberProgressTrack: { position: 'relative', height: 4, overflow: 'visible', borderRadius: 2, backgroundColor: '#173151' },
  memberProgressFill: { height: '100%', minWidth: 4, borderRadius: 2, backgroundColor: colors.volt, boxShadow: '0 0 7px rgba(232,255,61,.42)' },
  memberProgressMarker: { position: 'absolute', top: -1.5, width: 7, height: 7, borderRadius: 4, backgroundColor: '#A7B0B9', borderWidth: 2, borderColor: '#253955' },
  memberProgressMarkerFirst: { left: '38%' },
  memberProgressMarkerSecond: { left: '65%' },
  memberProgressMarkerThird: { left: '91%' },
  memberProgressHint: { color: colors.volt, fontFamily: fonts.displayBold, fontSize: 10, lineHeight: 12, letterSpacing: .8 },
  memberProgressHintCompact: { fontSize: 9, lineHeight: 11, letterSpacing: .45 },
  socialSkeleton: { gap: 10 },
  heroSkeleton: { minHeight: 544, padding: 12, borderRadius: 22, justifyContent: 'space-between', backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#30414E' },
  heroSkeletonTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  heroSkeletonHeading: { flex: 1, gap: 7 },
  skeletonRelic: { alignSelf: 'center' },
  heroSkeletonIdentity: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 8 },
  heroSkeletonIdentityCopy: { flex: 1, minWidth: 0, gap: 7 },
  heroSkeletonProgress: { gap: 7 },
  heroSkeletonProgressTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  warSkeletonSection: { marginTop: 16, gap: 14 },
  skeletonSectionHeading: { minHeight: 48, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  skeletonSectionCopy: { flex: 1, gap: 7 },
  warSkeletonBoard: { overflow: 'hidden', borderRadius: 18, backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#30414E' },
  warSkeletonHeader: { minHeight: 48, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  warSkeletonRow: { minHeight: 104, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderTopWidth: 1, borderTopColor: '#30414E' },
  warSkeletonRowCopy: { flex: 1, minWidth: 0, gap: 7 },
  memberSkeletonSection: { marginTop: 22, gap: 12 },
  memberSkeletonPanel: { overflow: 'hidden', borderRadius: 16, backgroundColor: '#100D13', borderWidth: 1, borderColor: '#30414E' },
  memberSkeletonRow: { minHeight: 104, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  memberSkeletonCopy: { flex: 1, minWidth: 0, gap: 8 },
  memberSkeletonStatsPanel: { overflow: 'hidden', borderRadius: 16, backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#30414E' },
  memberSkeletonStats: { minHeight: 88, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pressed: { opacity: .74 },
});
