import { StyleSheet } from 'react-native';

import { colors, fonts, layout, typography } from '@/src/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingHorizontal: 18, paddingTop: 6, paddingBottom: layout.tabBarContentInset + 12, gap: 10 },
  factionHero: { position: 'relative', minHeight: 544, overflow: 'hidden', padding: 12, borderRadius: 22, backgroundColor: '#06111A', borderWidth: 1, borderColor: '#284553' },
  heroTop: { zIndex: 6, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  heroHeading: { flex: 1, minWidth: 0 },
  heroEyebrow: { ...typography.eyebrow, color: colors.volt, letterSpacing: 1.1 },
  heroTitle: { ...typography.displayMedium, maxWidth: 205, marginTop: 4, color: '#F4F3EF' },
  levelPill: { flexShrink: 0, minHeight: 27, paddingHorizontal: 9, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(5,10,14,.82)', borderWidth: 1, borderColor: '#30414E' },
  levelDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.volt },
  levelText: { ...typography.label, color: '#D6DCE0', letterSpacing: .35 },
  relicQuestion: { color: colors.volt, fontFamily: fonts.display, fontSize: 22 },
  factionIdentity: { zIndex: 4, minHeight: 46, marginTop: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  factionSeal: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#687A2B' },
  factionIdentityCopy: { flex: 1, minWidth: 0 },
  factionName: { ...typography.bodyStrong, color: '#F6F7F5', letterSpacing: .1 },
  factionMeta: { ...typography.caption, marginTop: 3, color: '#9AA5AE' },
  factionGrowthBlock: { flexShrink: 0, flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  factionGrowth: { ...typography.metricSmall, color: colors.volt },
  factionGrowthLabel: { ...typography.eyebrow, color: '#9AA5AE', letterSpacing: .2 },
  progressBlock: { zIndex: 4, marginTop: 8 },
  relicForm: { ...typography.eyebrow, color: colors.volt, letterSpacing: .7 },
  progressHeadline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressValue: { ...typography.label, color: '#F4F6F2' },
  progressTrack: { height: 4, marginTop: 6, overflow: 'hidden', borderRadius: 3, backgroundColor: '#172029' },
  progressFill: { height: '100%', minWidth: 4, borderRadius: 3, backgroundColor: colors.volt },
  progressFoot: { minHeight: 14, marginTop: 6 },
  progressNext: { ...typography.caption, color: '#98A3AC' },
  rallyButton: { minHeight: 44, marginTop: 5, overflow: 'hidden', borderRadius: 12, backgroundColor: '#0F1510', borderWidth: 1, borderColor: '#58651E' },
  rallySurface: { flex: 1, width: '100%', minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, paddingHorizontal: 12 },
  rallyIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  supporterGlyph: { position: 'relative', width: 19, height: 17 },
  supporterHead: { position: 'absolute', width: 5, height: 5, borderRadius: 3, backgroundColor: colors.volt },
  supporterHeadLeft: { left: 0, top: 5 },
  supporterHeadCenter: { left: 7, top: 1 },
  supporterHeadRight: { right: 0, top: 5 },
  supporterShoulder: { position: 'absolute', height: 7, borderWidth: 1.5, borderBottomWidth: 0, borderColor: colors.volt, borderTopLeftRadius: 6, borderTopRightRadius: 6 },
  supporterShoulderLeft: { width: 8, left: 0, bottom: 0 },
  supporterShoulderCenter: { width: 10, left: 4.5, bottom: 2 },
  supporterShoulderRight: { width: 8, right: 0, bottom: 0 },
  rallyText: { ...typography.cardTitle, flexShrink: 1, color: colors.volt, fontSize: 14, lineHeight: 18, letterSpacing: .16, textAlign: 'center' },
  warSection: { marginTop: 16, gap: 14 },
  warSectionHeading: { position: 'relative', paddingTop: 4, alignItems: 'flex-start' },
  sectionHeading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  sectionHeadingCopy: { flex: 1, minWidth: 0 },
  sectionEyebrow: { color: colors.volt, fontFamily: fonts.bold, fontSize: 11, lineHeight: 14, letterSpacing: .8 },
  sectionTitle: { marginTop: 5, color: '#F3F5F5', fontFamily: fonts.display, fontSize: 27, lineHeight: 29, letterSpacing: -.25 },
  warSectionTitle: { fontSize: 25, lineHeight: 27, letterSpacing: -.4 },
  warSectionTitleCompact: { maxWidth: 230, fontSize: 22, lineHeight: 24 },
  warPeriod: { position: 'absolute', top: 2, right: 0, minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 1 },
  warPeriodDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.volt, boxShadow: '0 0 8px rgba(232,255,61,.5)' },
  warPeriodText: { color: '#F1F3EF', fontFamily: fonts.bold, fontSize: 13, lineHeight: 17, letterSpacing: .35 },
  warBoard: { position: 'relative', overflow: 'hidden', borderRadius: 18, borderWidth: 1, borderColor: '#30414E', boxShadow: '0 12px 24px rgba(0,0,0,.28)' },
  warTableHeader: { minHeight: 48, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#30414E' },
  warTableHeaderCompact: { paddingHorizontal: 10 },
  warTableHeading: { color: '#9099A1', fontFamily: fonts.bold, fontSize: 11, lineHeight: 14, letterSpacing: .35 },
  warTableHeadingCompact: { fontSize: 9, lineHeight: 12 },
  warTableRankHeading: { width: 50 },
  warTableRankHeadingCompact: { width: 44 },
  warTableFactionHeading: { flex: 1, minWidth: 0 },
  warTableSupportersHeading: { width: 68, fontSize: 9, lineHeight: 12, textAlign: 'center' },
  warTableSupportersHeadingCompact: { width: 52, fontSize: 7, lineHeight: 10 },
  warTableRow: { position: 'relative', minHeight: 104, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
  warTableRowCompact: { minHeight: 92, paddingHorizontal: 8, gap: 4 },
  warTableRowDivider: { borderBottomWidth: 1, borderBottomColor: '#30414E' },
  warTableRowMine: { backgroundColor: 'rgba(255,106,33,.06)' },
  warTableRail: { position: 'absolute', top: 0, bottom: 0, left: 0, width: 4 },
  warTableRank: { width: 42, color: colors.volt, fontFamily: fonts.display, fontSize: 35, lineHeight: 37 },
  warTableRankCompact: { width: 30, fontSize: 27, lineHeight: 29 },
  warTableShield: { position: 'relative', flexShrink: 0, alignItems: 'center', justifyContent: 'center' },
  warTableShieldLogo: { position: 'absolute', top: '21%', right: 0, bottom: '17%', left: 0, alignItems: 'center', justifyContent: 'center' },
  warTableIdentity: { flex: 1, minWidth: 0 },
  warTableName: { color: '#F3F5F6', fontFamily: fonts.bold, fontSize: 15, lineHeight: 19, letterSpacing: -.4 },
  warTableNameCompact: { fontSize: 11, lineHeight: 15, letterSpacing: -.55 },
  warTableMine: { marginTop: 4, color: colors.volt, fontFamily: fonts.bold, fontSize: 11, lineHeight: 14, letterSpacing: .45 },
  warTableMineCompact: { fontSize: 8, lineHeight: 11, letterSpacing: 0 },
  warTableSupporters: { width: 64, flexShrink: 0, alignItems: 'center' },
  warTableSupportersCompact: { width: 46 },
  warTableSupporterValue: { color: '#F4F6F7', fontFamily: fonts.display, fontSize: 30, lineHeight: 31 },
  warTableSupporterValueCompact: { fontSize: 26, lineHeight: 27 },
  warTableSupporterLabel: { marginTop: 4, color: '#949DA4', fontFamily: fonts.bold, fontSize: 8, lineHeight: 11 },
  warTableSupporterLabelCompact: { fontSize: 7, lineHeight: 9 },
  memberSection: { marginTop: 22, gap: 12 },
  memberPlacement: { alignSelf: 'flex-end', marginBottom: 3, color: colors.volt, fontFamily: fonts.bold, fontSize: 12, lineHeight: 15, letterSpacing: .2 },
  memberIdentityCard: { position: 'relative', overflow: 'hidden', borderRadius: 16, borderWidth: 1, borderColor: '#30414E', boxShadow: '0 10px 20px rgba(0,0,0,.24)' },
  memberIdentityTopRule: { position: 'absolute', zIndex: 2, top: 0, right: 12, left: 12, height: 1, backgroundColor: colors.volt },
  memberStatsPanel: { overflow: 'hidden', borderRadius: 16, borderWidth: 1, borderColor: '#30414E', boxShadow: '0 10px 20px rgba(0,0,0,.2)' },
  memberStats: { minHeight: 88, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center' },
  memberStat: { flex: 1, minWidth: 0, minHeight: 80, alignItems: 'center', justifyContent: 'center' },
  memberStatDivider: { width: 1, height: 46, backgroundColor: '#273229' },
  memberStatValue: { color: '#F1F3F2', fontFamily: fonts.display, fontSize: 27, lineHeight: 29 },
  memberStatValueFeatured: { color: colors.volt },
  memberStatLabel: { marginTop: 5, color: '#8E989D', fontFamily: fonts.medium, fontSize: 11, lineHeight: 14, letterSpacing: .2, textAlign: 'center' },
  memberRow: { minHeight: 104, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  memberRowCompact: { paddingHorizontal: 10, gap: 8 },
  memberRowMine: { backgroundColor: 'rgba(232,255,61,.025)' },
  memberRowRank: { width: 42, color: '#8C98A2', fontFamily: fonts.display, fontSize: 27, lineHeight: 29 },
  memberRowRankCompact: { width: 36, fontSize: 25, lineHeight: 27 },
  memberRowRankMine: { color: colors.volt },
  memberIdentityDivider: { width: 1, height: 56, backgroundColor: '#152633' },
  memberIdentityDividerCompact: { height: 48 },
  memberAvatar: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0B1218', borderWidth: 2 },
  memberAvatarCompact: { width: 48, height: 48, borderRadius: 24 },
  memberAvatarText: { color: '#CDD3D5', fontFamily: fonts.bold, fontSize: 12, lineHeight: 15 },
  memberCopy: { flex: 1, minWidth: 0 },
  memberName: { color: '#F0F2F3', fontFamily: fonts.bold, fontSize: 17, lineHeight: 21 },
  memberNameCompact: { fontSize: 14, lineHeight: 18 },
  memberMeta: { marginTop: 3, color: colors.volt, fontFamily: fonts.medium, fontSize: 11, lineHeight: 14 },
  socialSkeleton: { gap: 10 },
  heroSkeleton: { minHeight: 544, padding: 12, borderRadius: 22, justifyContent: 'space-between', backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#30414E' },
  heroSkeletonTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  heroSkeletonHeading: { flex: 1, gap: 7 },
  skeletonRelic: { alignSelf: 'center' },
  heroSkeletonIdentity: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 8 },
  heroSkeletonIdentityCopy: { flex: 1, minWidth: 0, gap: 7 },
  heroSkeletonProgress: { gap: 7 },
  heroSkeletonProgressTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  warSkeletonSection: { marginTop: 16, gap: 14 },
  skeletonSectionHeading: { minHeight: 48, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  skeletonSectionCopy: { flex: 1, gap: 7 },
  warSkeletonBoard: { overflow: 'hidden', borderRadius: 18, backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#30414E' },
  warSkeletonHeader: { minHeight: 48, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  warSkeletonRow: { minHeight: 104, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderTopWidth: 1, borderTopColor: '#30414E' },
  warSkeletonRowCopy: { flex: 1, minWidth: 0, gap: 7 },
  memberSkeletonSection: { marginTop: 22, gap: 12 },
  memberSkeletonPanel: { overflow: 'hidden', borderRadius: 16, backgroundColor: '#100D13', borderWidth: 1, borderColor: '#30414E' },
  memberSkeletonRow: { minHeight: 104, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  memberSkeletonCopy: { flex: 1, minWidth: 0, gap: 8 },
  memberSkeletonStatsPanel: { overflow: 'hidden', borderRadius: 16, backgroundColor: '#0B1218', borderWidth: 1, borderColor: '#30414E' },
  memberSkeletonStats: { minHeight: 88, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pressed: { opacity: .74 },
});
