import { StyleSheet } from 'react-native';

import { colors, fonts, typography } from '@/src/theme';

export const JOURNEY_VIEWBOX_WIDTH = 360;
export const JOURNEY_FIRST_Y = 72;
export const JOURNEY_GRADE_SPACING = 116;

export const journeyStyles = StyleSheet.create({
  card: {
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingTop: 17,
    paddingBottom: 14,
    borderRadius: 28,
    backgroundColor: 'rgba(6,24,35,.9)',
    borderWidth: 1,
    borderColor: '#486171',
    boxShadow: '0 20px 48px rgba(0,0,0,.42)',
  },
  atmosphere: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
    opacity: 0.42,
  },
  atmosphereVeil: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  leftVignette: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 116,
    backgroundColor: 'rgba(2,8,16,.24)',
  },
  rightVignette: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 34,
    backgroundColor: 'rgba(2,8,16,.18)',
  },
  header: {
    zIndex: 5,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  title: {
    ...typography.bodyStrong,
    flexShrink: 0,
    color: colors.volt,
    fontSize: 13,
    lineHeight: 17,
    letterSpacing: 0.7,
  },
  headerMeta: {
    minWidth: 0,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
  },
  seasonName: {
    ...typography.label,
    minWidth: 0,
    flexShrink: 1,
    color: '#9BA5AF',
    fontSize: 11,
    letterSpacing: 0.5,
    textAlign: 'right',
  },
  infoButton: {
    width: 28,
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: 'rgba(4,10,15,.82)',
    borderWidth: 1,
    borderColor: '#385161',
  },
  infoButtonActive: {
    borderColor: '#B3C92D',
    backgroundColor: 'rgba(232,255,61,.09)',
  },
  infoGlyph: {
    color: '#B9C5CF',
    fontFamily: fonts.bold,
    fontSize: 13,
    lineHeight: 16,
  },
  journey: {
    position: 'relative',
    zIndex: 2,
    width: '100%',
  },
  pathLayer: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
  },
  pathSvg: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
  },
  gradeLabel: {
    position: 'absolute',
    left: 0,
    width: 116,
    minHeight: 48,
    justifyContent: 'center',
  },
  gradeLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  gradeName: {
    ...typography.bodyStrong,
    flexShrink: 0,
    color: '#A7B2BD',
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: 0.55,
  },
  gradeNameCurrent: {
    color: '#F3F4F1',
  },
  gradeNameAcquired: {
    color: '#C9D5DE',
  },
  gradeRule: {
    flex: 1,
    height: 1,
    minWidth: 9,
    backgroundColor: '#9A5F38',
  },
  gradeRuleCurrent: {
    backgroundColor: colors.volt,
    boxShadow: '0 0 8px rgba(232,255,61,.55)',
  },
  gradeRange: {
    ...typography.eyebrow,
    marginTop: 4,
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.42,
  },
  gradeRangeCurrent: {
    color: '#A7B4BF',
  },
  node: {
    position: 'absolute',
    zIndex: 3,
    width: 158,
    height: 112,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  pedestalRoot: {
    position: 'relative',
    width: 158,
    height: 112,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  pedestalHalo: {
    position: 'absolute',
    bottom: 13,
    width: 128,
    height: 46,
    borderRadius: 64,
    opacity: 0,
  },
  pedestalHaloActive: {
    opacity: 0.2,
  },
  pedestalImage: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    width: 158,
    height: 79,
  },
  pedestalFuture: {
    opacity: 0.48,
  },
  pedestalAcquired: {
    opacity: 0.76,
  },
  pedestalCurrent: {
    opacity: 1,
  },
  emblem: {
    position: 'absolute',
    top: -5,
    zIndex: 2,
  },
  activeContour: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  metrics: {
    zIndex: 5,
    marginTop: 2,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: 'rgba(91,111,126,.28)',
  },
  metricColumns: {
    minHeight: 94,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  metricColumn: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  metricDivider: {
    width: 1,
    marginVertical: 5,
    backgroundColor: 'rgba(108,127,142,.34)',
  },
  metricLabel: {
    ...typography.eyebrow,
    color: '#8793A0',
    fontSize: 11,
    letterSpacing: 0.7,
  },
  ratingValue: {
    marginTop: 8,
    color: '#F3F4F1',
    fontFamily: fonts.display,
    fontSize: 46,
    lineHeight: 47,
    letterSpacing: -1.8,
    fontVariant: ['tabular-nums'],
  },
  progressTrack: {
    height: 7,
    marginTop: 10,
    overflow: 'hidden',
    borderRadius: 4,
    backgroundColor: '#1C2A34',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  progressPercent: {
    ...typography.label,
    marginTop: 7,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  metricHint: {
    ...typography.label,
    marginTop: 13,
    color: '#A5B1BB',
    fontSize: 11,
    letterSpacing: 0.38,
    textAlign: 'center',
  },
  action: {
    zIndex: 5,
    minHeight: 56,
    marginTop: 17,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: colors.volt,
    boxShadow: '0 7px 22px rgba(210,236,38,.16)',
  },
  actionPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  actionText: {
    color: '#070A0C',
    fontFamily: fonts.bold,
    fontSize: 13,
    lineHeight: 17,
    letterSpacing: 0.75,
  },
  actionArrow: {
    position: 'absolute',
    right: 18,
    color: '#070A0C',
    fontFamily: fonts.bold,
    fontSize: 22,
    lineHeight: 24,
  },
});
