import type { TeamPackDefinition } from './types';

// Historical definitions: retain IDs and artwork for existing ownership.
// Visibility is controlled by the catalog assembly in teamPackCatalog.ts.

const LOL_GOLD = '#D6B56A';
const VALORANT_RED = '#FF4655';
const ROCKET_LEAGUE_ORANGE = '#FF8A24';

export const LEAGUE_OF_LEGENDS_COLLECTION_PACK: TeamPackDefinition = {
  id: 'league-of-legends-collection',
  kind: 'game_collection',
  brandKey: 'league-of-legends',
  name: 'Pack League of Legends',
  title: 'LEAGUE OF LEGENDS',
  subtitle: 'ICÔNES DE RUNETERRA',
  description: 'Cinq pièces iconiques réunies dans une galerie de pierre, d’or et de lumière cyan.',
  accent: LOL_GOLD,
  price: 900,
  licenseHolder: 'Riot Games',
  hero: require('../../../../assets/shop/collections/league-of-legends/league-of-legends-collection-hero.png'),
  items: [
    {
      id: 'lol-infinity-edge',
      number: 1,
      name: 'Lame d’Infini',
      description: 'Une réplique de collection aux finitions acier, or et cristal azur.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: LOL_GOLD,
      equipByDefault: false,
      roomKind: 'core',
      roomSlot: 'left-free',
      image: require('../../../../assets/shop/collections/league-of-legends/items/infinity-edge.png'),
    },
    {
      id: 'lol-nexus-fragment',
      number: 2,
      name: 'Fragment du Nexus',
      description: 'Un fragment azur suspendu, parcouru d’une énergie cristalline.',
      slot: 'apparence_core',
      rarity: 'legendaire',
      accent: '#35C8FF',
      equipByDefault: false,
      roomKind: 'core',
      roomSlot: 'left-extra',
      image: require('../../../../assets/shop/collections/league-of-legends/items/nexus-fragment.png'),
    },
    {
      id: 'lol-jinx-fishbones-gallery',
      number: 3,
      name: 'Jinx & Fishbones',
      description: 'La pièce centrale de la collection, dressée avec Fishbones sur un podium noir et or.',
      slot: 'vitrine_supports',
      rarity: 'legendaire',
      accent: '#55C9FF',
      equipByDefault: true,
      roomKind: 'trophy',
      roomSlot: 'trophy',
      image: require('../../../../assets/shop/collections/league-of-legends/items/jinx-fishbones.png'),
    },
    {
      id: 'lol-baron-nashor',
      number: 4,
      name: 'Baron Nashor',
      description: 'Une sculpture violette monumentale surgissant d’un bassin d’énergie du Néant.',
      slot: 'apparence_core',
      rarity: 'legendaire',
      accent: '#9B5CFF',
      equipByDefault: false,
      roomKind: 'trophy',
      roomSlot: 'right-extra',
      image: require('../../../../assets/shop/collections/league-of-legends/items/baron-nashor.png'),
    },
    {
      id: 'lol-vision-ward',
      number: 5,
      name: 'Balise de vision',
      description: 'Une balise dorée protégée par une cloche de verre et un halo ambré.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#F3B84B',
      equipByDefault: false,
      roomKind: 'ring',
      roomSlot: 'right-free',
      image: require('../../../../assets/shop/collections/league-of-legends/items/vision-ward.png'),
    },
  ],
};

export const VALORANT_COLLECTION_PACK: TeamPackDefinition = {
  id: 'valorant-collection',
  kind: 'game_collection',
  brandKey: 'valorant',
  name: 'Pack Valorant',
  title: 'VALORANT',
  subtitle: 'PROTOCOLE RADIANT',
  description: 'Cinq pièces iconiques réunies dans une galerie de pierre, de métal et de lumière corail.',
  accent: VALORANT_RED,
  price: 900,
  licenseHolder: 'Riot Games',
  hero: require('../../../../assets/shop/collections/valorant/valorant-collection-hero.png'),
  items: [
    {
      id: 'valorant-vandal',
      number: 1,
      name: 'Vandal',
      description: 'Une réplique blanche et graphite sertie d’un noyau corail lumineux.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: VALORANT_RED,
      equipByDefault: false,
      roomKind: 'core',
      roomSlot: 'left-free',
      image: require('../../../../assets/shop/collections/valorant/items/vandal.png'),
    },
    {
      id: 'valorant-spike',
      number: 2,
      name: 'Spike',
      description: 'Le dispositif de radianite suspendu au-dessus d’un socle parcouru d’étincelles rouges.',
      slot: 'apparence_core',
      rarity: 'legendaire',
      accent: VALORANT_RED,
      equipByDefault: false,
      roomKind: 'core',
      roomSlot: 'left-extra',
      image: require('../../../../assets/shop/collections/valorant/items/spike.png'),
    },
    {
      id: 'valorant-jett-gallery',
      number: 3,
      name: 'Jett',
      description: 'La pièce centrale de la collection, portée par une spirale de vent et de lames.',
      slot: 'vitrine_supports',
      rarity: 'legendaire',
      accent: '#9FE8FF',
      equipByDefault: true,
      roomKind: 'trophy',
      roomSlot: 'trophy',
      image: require('../../../../assets/shop/collections/valorant/items/jett.png'),
    },
    {
      id: 'valorant-omen',
      number: 4,
      name: 'Omen',
      description: 'Un buste d’Omen émergeant d’une nappe d’ombre violette.',
      slot: 'apparence_core',
      rarity: 'legendaire',
      accent: '#8A5CFF',
      equipByDefault: false,
      roomKind: 'trophy',
      roomSlot: 'right-extra',
      image: require('../../../../assets/shop/collections/valorant/items/omen.png'),
    },
    {
      id: 'valorant-wingman',
      number: 5,
      name: 'Wingman',
      description: 'Le compagnon jaune de Gekko protégé sous une cloche de verre de collection.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#D8F34A',
      equipByDefault: false,
      roomKind: 'ring',
      roomSlot: 'right-free',
      image: require('../../../../assets/shop/collections/valorant/items/wingman.png'),
    },
  ],
};

export const ROCKET_LEAGUE_COLLECTION_PACK: TeamPackDefinition = {
  id: 'rocket-league-collection',
  kind: 'game_collection',
  brandKey: 'rocket-league',
  name: 'Pack Rocket League',
  title: 'ROCKET LEAGUE',
  subtitle: 'BLUE & ORANGE ARENA',
  description: 'Cinq pièces iconiques réunies dans une galerie traversée par l’énergie bleue et orange.',
  accent: ROCKET_LEAGUE_ORANGE,
  price: 900,
  licenseHolder: 'Psyonix',
  hero: require('../../../../assets/shop/collections/rocket-league/rocket-league-collection-hero.png'),
  items: [
    {
      id: 'rocket-league-zomba-wheel',
      number: 1,
      name: 'Roue Zomba',
      description: 'Une roue de collection dont le moyeu irradie un motif d’énergie bleu, rose et orange.',
      slot: 'apparence_core',
      rarity: 'legendaire',
      accent: '#35A8FF',
      equipByDefault: false,
      roomKind: 'ring',
      roomSlot: 'left-free',
      image: require('../../../../assets/shop/collections/rocket-league/items/zomba-wheel.png'),
    },
    {
      id: 'rocket-league-boost-100',
      number: 2,
      name: 'Boost 100',
      description: 'Un orbe doré suspendu au-dessus d’un flux continu de particules de boost.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#FFBE3D',
      equipByDefault: false,
      roomKind: 'core',
      roomSlot: 'left-extra',
      image: require('../../../../assets/shop/collections/rocket-league/items/boost-100.png'),
    },
    {
      id: 'rocket-league-octane-gallery',
      number: 3,
      name: 'Octane',
      description: 'La pièce centrale de la collection, un Octane bleu et orange en sustentation.',
      slot: 'vitrine_supports',
      rarity: 'legendaire',
      accent: '#2C9CFF',
      equipByDefault: true,
      roomKind: 'trophy',
      roomSlot: 'trophy',
      image: require('../../../../assets/shop/collections/rocket-league/items/octane.png'),
    },
    {
      id: 'rocket-league-arena-ball',
      number: 4,
      name: 'Ballon d’arène',
      description: 'Le ballon blindé des arènes, marqué par les lumières des deux camps.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#7CCAFF',
      equipByDefault: false,
      roomKind: 'trophy',
      roomSlot: 'right-extra',
      image: require('../../../../assets/shop/collections/rocket-league/items/arena-ball.png'),
    },
    {
      id: 'rocket-league-goal-explosion',
      number: 5,
      name: 'Explosion de but',
      description: 'Un impact bleu et orange figé dans un but miniature de collection.',
      slot: 'apparence_core',
      rarity: 'legendaire',
      accent: ROCKET_LEAGUE_ORANGE,
      equipByDefault: false,
      roomKind: 'core',
      roomSlot: 'right-free',
      image: require('../../../../assets/shop/collections/rocket-league/items/goal-explosion.png'),
    },
  ],
};
