import type { TeamPackDefinition } from './types';

const NEON_CYAN = '#58DFFF';
const FORGE_ORANGE = '#F06A3A';
const CIRCUIT_LIME = '#C7F000';

export const NEON_PROTOCOL_PACK: TeamPackDefinition = {
  id: 'neon-protocol',
  kind: 'original',
  brandKey: 'clutch-originals',
  name: 'Pack Protocole Néon',
  title: 'PROTOCOLE NÉON',
  subtitle: 'SYNAPSE // ARCHITECTE',
  description: 'Huit cosmétiques originaux pour transformer ta Vitrine en chambre Synapse.',
  accent: NEON_CYAN,
  price: 1200,
  licenseHolder: 'Clutch',
  hero: require('../../../../assets/shop/packs/neon-protocol/neon-protocol-hero.png'),
  items: [
    {
      id: 'neon-protocol-room',
      number: 1,
      name: 'Salle Synapse',
      description: 'Une chambre orbitale graphite ouverte sur l’espace et soulignée de cyan néon.',
      slot: 'vitrine_eclairage',
      rarity: 'legendaire',
      accent: NEON_CYAN,
      equipByDefault: true,
      image: require('../../../../assets/shop/packs/neon-protocol/neon-protocol-room-empty.png'),
    },
    {
      id: 'neon-protocol-armor-vega',
      number: 2,
      name: 'Armure Vega',
      description: 'Une armure céramique ivoire sur exostructure graphite, traversée de lignes cyan.',
      slot: 'vitrine_maillot',
      rarity: 'epique',
      accent: NEON_CYAN,
      equipByDefault: true,
      roomKind: 'jersey',
      roomSlot: 'jersey',
      image: require('../../../../assets/shop/front-facing/neon-protocol-armor-vega.png'),
    },
    {
      id: 'neon-protocol-glyph-node',
      number: 3,
      name: 'Glyphe Nœud',
      description: 'Trois plaques ivoire convergent autour d’un nœud d’énergie magenta.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#E27AFF',
      equipByDefault: true,
      roomKind: 'core',
      roomSlot: 'right-extra',
      image: require('../../../../assets/shop/front-facing/neon-protocol-glyph-node.png'),
    },
    {
      id: 'neon-protocol-banner-phase',
      number: 4,
      name: 'Bannière Phase',
      description: 'Une bannière graphite portant le glyphe du Protocole et ses liserés de phase.',
      slot: 'carte_profil',
      rarity: 'rare',
      accent: NEON_CYAN,
      equipByDefault: false,
      roomKind: 'banner',
      roomSlot: 'left-extra',
      image: require('../../../../assets/shop/packs/neon-protocol/items/banner-phase.png'),
    },
    {
      id: 'neon-protocol-null-totem',
      number: 5,
      name: 'Totem Null',
      description: 'Une colonne de modules graphite maintenus en équilibre par un flux cyan.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: NEON_CYAN,
      equipByDefault: false,
      roomKind: 'trophy',
      roomSlot: 'trophy',
      image: require('../../../../assets/shop/front-facing/neon-protocol-null-totem.png'),
    },
    {
      id: 'neon-protocol-pioneer-badge',
      number: 6,
      name: 'Badge Pionnier',
      description: 'Un badge octogonal cerclé d’une orbite métallique et signé du glyphe Nœud.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#E27AFF',
      equipByDefault: false,
      roomKind: 'badge',
      roomSlot: 'badge',
      image: require('../../../../assets/shop/packs/neon-protocol/items/pioneer-badge.png'),
    },
    {
      id: 'neon-protocol-phase-frame',
      number: 7,
      name: 'Cadre Phase',
      description: 'Un cadre graphite angulaire aux inserts cyan et à l’éclat magenta.',
      slot: 'cadre_profil',
      rarity: 'epique',
      accent: NEON_CYAN,
      equipByDefault: true,
      roomKind: 'frame',
      roomSlot: 'left-free',
      image: require('../../../../assets/shop/packs/neon-protocol/items/phase-frame.png'),
    },
    {
      id: 'neon-protocol-impulse-effect',
      number: 8,
      name: 'Effet Impulsion',
      description: 'Une impulsion cyan et magenta traverse la Vitrine avant de se stabiliser en halo.',
      slot: 'effet_faction',
      rarity: 'legendaire',
      accent: '#54CFFF',
      equipByDefault: true,
      image: require('../../../../assets/shop/packs/neon-protocol/items/impulse-effect.png'),
    },
  ],
};

export const MYTHS_FORGE_PACK: TeamPackDefinition = {
  id: 'mythes-forge',
  kind: 'original',
  brandKey: 'clutch-originals',
  name: 'Pack Mythes de la Forge',
  title: 'MYTHES DE LA FORGE',
  subtitle: 'ORÉA // MAÎTRE-FORGE',
  description: 'Huit cosmétiques originaux façonnés dans le basalte, le cuivre et la braise.',
  accent: FORGE_ORANGE,
  price: 1200,
  licenseHolder: 'Clutch',
  hero: require('../../../../assets/shop/packs/mythes-forge/mythes-forge-hero.png'),
  items: [
    {
      id: 'mythes-forge-room',
      number: 1,
      name: 'Forge des Failles',
      description: 'Une galerie de basalte traversée de veines de braise et de cuivre patiné.',
      slot: 'vitrine_eclairage',
      rarity: 'legendaire',
      accent: FORGE_ORANGE,
      equipByDefault: true,
      image: require('../../../../assets/shop/packs/mythes-forge/mythes-forge-room-empty.png'),
    },
    {
      id: 'mythes-forge-armor-orea',
      number: 2,
      name: 'Armure Oréa',
      description: 'Une cuirasse ivoire et graphite forgée autour d’un noyau de cuivre incandescent.',
      slot: 'vitrine_maillot',
      rarity: 'epique',
      accent: '#E7DCCB',
      equipByDefault: true,
      roomKind: 'jersey',
      roomSlot: 'jersey',
      image: require('../../../../assets/shop/front-facing/mythes-forge-armor-orea.png'),
    },
    {
      id: 'mythes-forge-ember-sigil',
      number: 3,
      name: 'Sigil de Braise',
      description: 'Un anneau fendu serti de trois braises qui pulse au rythme de la Forge.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: FORGE_ORANGE,
      equipByDefault: true,
      roomKind: 'core',
      roomSlot: 'right-extra',
      image: require('../../../../assets/shop/front-facing/mythes-forge-ember-sigil.png'),
    },
    {
      id: 'mythes-forge-strata-banner',
      number: 4,
      name: 'Bannière Strate',
      description: 'Une bannière minérale noire, marquée d’un tracé cuivre original sans emblème tiers.',
      slot: 'carte_profil',
      rarity: 'rare',
      accent: '#C9784B',
      equipByDefault: false,
      roomKind: 'banner',
      roomSlot: 'left-extra',
      image: require('../../../../assets/shop/packs/mythes-forge/items/strata-banner.png'),
    },
    {
      id: 'mythes-forge-basalt-totem',
      number: 5,
      name: 'Totem Basalte',
      description: 'Une colonne de roche noire maintenue par des bagues d’ivoire et de cuivre.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: FORGE_ORANGE,
      equipByDefault: false,
      roomKind: 'trophy',
      roomSlot: 'trophy',
      image: require('../../../../assets/shop/front-facing/mythes-forge-basalt-totem.png'),
    },
    {
      id: 'mythes-forge-artisan-badge',
      number: 6,
      name: 'Badge Artisan',
      description: 'Un badge hexagonal taillé dans la pierre, traversé d’un sigil de cuivre incandescent.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#43BFC1',
      equipByDefault: false,
      roomKind: 'badge',
      roomSlot: 'badge',
      image: require('../../../../assets/shop/packs/mythes-forge/items/artisan-badge.png'),
    },
    {
      id: 'mythes-forge-rift-frame',
      number: 7,
      name: 'Cadre Fissure',
      description: 'Un cadre de basalte éclaté, consolidé par des angles de cuivre et d’ivoire.',
      slot: 'cadre_profil',
      rarity: 'epique',
      accent: FORGE_ORANGE,
      equipByDefault: true,
      roomKind: 'frame',
      roomSlot: 'left-free',
      image: require('../../../../assets/shop/packs/mythes-forge/items/rift-frame.png'),
    },
    {
      id: 'mythes-forge-resonance-effect',
      number: 8,
      name: 'Effet Résonance',
      description: 'Des cercles telluriques orange et turquoise propagent une onde dans toute la Vitrine.',
      slot: 'effet_faction',
      rarity: 'legendaire',
      accent: FORGE_ORANGE,
      equipByDefault: true,
      image: require('../../../../assets/shop/packs/mythes-forge/items/resonance-effect.png'),
    },
  ],
};

export const CIRCUIT_ZERO_PACK: TeamPackDefinition = {
  id: 'circuit-zero',
  kind: 'original',
  brandKey: 'clutch-originals',
  name: 'Pack Circuit Zéro',
  title: 'CIRCUIT ZÉRO',
  subtitle: 'KAIROS-6 // CHRONONAUTE',
  description: 'Huit cosmétiques originaux issus d’un programme aérodynamique aux lignes ivoire, graphite et vert acide.',
  accent: CIRCUIT_LIME,
  price: 1200,
  licenseHolder: 'Clutch',
  hero: require('../../../../assets/shop/packs/circuit-zero/circuit-zero-hero.png'),
  items: [
    {
      id: 'circuit-zero-room',
      number: 1,
      name: 'Hangar Vectoriel',
      description: 'Un tunnel d’essai graphite et ivoire où chaque station suit la trajectoire du Kairos-6.',
      slot: 'vitrine_eclairage',
      rarity: 'legendaire',
      accent: CIRCUIT_LIME,
      equipByDefault: true,
      image: require('../../../../assets/shop/packs/circuit-zero/circuit-zero-room-empty.png'),
    },
    {
      id: 'circuit-zero-kairos-6',
      number: 2,
      name: 'Kairos-6',
      description: 'Un prototype à six roues conçu pour fendre l’air et laisser un sillage vert acide.',
      slot: 'vitrine_maillot',
      rarity: 'epique',
      accent: '#EDE5D7',
      equipByDefault: true,
      roomKind: 'jersey',
      roomSlot: 'jersey',
      image: require('../../../../assets/shop/packs/circuit-zero/items/kairos-6.png'),
    },
    {
      id: 'circuit-zero-zero-glyph',
      number: 3,
      name: 'Glyphe Zéro',
      description: 'Un anneau ouvert entre deux ailettes graphite, ponctué d’un nœud magenta.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: CIRCUIT_LIME,
      equipByDefault: true,
      roomKind: 'core',
      roomSlot: 'right-extra',
      image: require('../../../../assets/shop/front-facing/circuit-zero-zero-glyph.png'),
    },
    {
      id: 'circuit-zero-sector-banner',
      number: 4,
      name: 'Bannière Secteur',
      description: 'Une bannière d’essai graphite traversée de repères ivoire, lime et magenta.',
      slot: 'carte_profil',
      rarity: 'rare',
      accent: CIRCUIT_LIME,
      equipByDefault: false,
      roomKind: 'banner',
      roomSlot: 'left-extra',
      image: require('../../../../assets/shop/front-facing/circuit-zero-sector-banner.png'),
    },
    {
      id: 'circuit-zero-delta-totem',
      number: 5,
      name: 'Totem Delta',
      description: 'Des profils d’aile superposés autour d’un axe de mesure magenta.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: CIRCUIT_LIME,
      equipByDefault: false,
      roomKind: 'trophy',
      roomSlot: 'trophy',
      image: require('../../../../assets/shop/front-facing/circuit-zero-delta-totem.png'),
    },
    {
      id: 'circuit-zero-pilot-badge',
      number: 6,
      name: 'Badge Pilote',
      description: 'Un insigne de pilote à boucle ouverte, usiné dans l’ivoire et le graphite.',
      slot: 'apparence_core',
      rarity: 'epique',
      accent: '#EA4FC9',
      equipByDefault: false,
      roomKind: 'badge',
      roomSlot: 'badge',
      image: require('../../../../assets/shop/front-facing/circuit-zero-pilot-badge.png'),
    },
    {
      id: 'circuit-zero-wake-frame',
      number: 7,
      name: 'Cadre Sillage',
      description: 'Un cadre graphite dont les angles capturent une traînée lime et magenta.',
      slot: 'cadre_profil',
      rarity: 'epique',
      accent: CIRCUIT_LIME,
      equipByDefault: true,
      roomKind: 'frame',
      roomSlot: 'left-free',
      image: require('../../../../assets/shop/packs/circuit-zero/items/wake-frame.png'),
    },
    {
      id: 'circuit-zero-afterimage-effect',
      number: 8,
      name: 'Effet Postimage',
      description: 'Trois silhouettes du Kairos-6 traversent la Vitrine avant de fusionner sur la ligne de mesure.',
      slot: 'effet_faction',
      rarity: 'legendaire',
      accent: CIRCUIT_LIME,
      equipByDefault: true,
      image: require('../../../../assets/shop/packs/circuit-zero/items/afterimage-effect.png'),
    },
  ],
};
