import type { AchievementBadgeDefinition, BadgeId } from './types';

export const ACHIEVEMENT_BADGE_CATALOG: readonly AchievementBadgeDefinition[] = [
  { id: 'first_signal', name: 'Premier Signal', description: 'Le premier verdict inscrit dans ton parcours officiel.', condition: 'Obtenir le verdict de son premier call officiel.', category: 'calls', rarity: 'common', visualFamily: 'circular-target-cyan', accent: '#31D7E2', isSecret: false },
  { id: 'placement_revealed', name: 'Placement révélé', description: 'Ton premier grade de saison a quitté l’ombre.', condition: 'Terminer les 5 verdicts de placement.', category: 'season', rarity: 'common', visualFamily: 'circular-target-silver', accent: '#63B8FF', isSecret: false },
  { id: 'rising_streak', name: 'Série montante', description: 'Cinq lectures justes ont construit le même élan.', condition: 'Réussir 5 calls consécutifs durant une même saison.', category: 'calls', rarity: 'rare', visualFamily: 'chevron-shield-volt', accent: '#E8FF3D', isSecret: false },
  { id: 'clutch_moment', name: 'Instant Clutch', description: 'La décision juste au moment où tout pouvait basculer.', condition: 'Réussir le call d’une manche décisive d’un BO3 ou BO5 à égalité.', category: 'calls', rarity: 'rare', visualFamily: 'split-diamond-amber', accent: '#FFB84D', isSecret: false },
  { id: 'sharp_eye', name: 'Œil juste', description: 'Ton regard a traversé vingt-cinq verdicts.', condition: 'Cumuler 25 calls corrects.', category: 'calls', rarity: 'rare', visualFamily: 'mechanism-cyan', accent: '#31D7E2', isSecret: false },
  { id: 'centurion', name: 'Centurion', description: 'Cent calls officiels composent désormais ton registre.', condition: 'Atteindre 100 calls officiels finalisés.', category: 'calls', rarity: 'rare', visualFamily: 'chevron-shield-silver', accent: '#CBD4DB', isSecret: false },
  { id: 'strategist', name: 'Stratège', description: 'La précision tient sur la durée d’une vraie campagne.', condition: 'Obtenir au moins 70 % de réussite sur 50 calls officiels durant une saison.', category: 'season', rarity: 'epic', visualFamily: 'compass-sapphire', accent: '#2F78FF', isSecret: false },
  { id: 'versatile', name: 'Polyvalent', description: 'Tes lectures restent justes sur plusieurs terrains.', condition: 'Réussir au moins un call dans 5 compétitions différentes.', category: 'calls', rarity: 'rare', visualFamily: 'compass-five', accent: '#4DD9F1', isSecret: false },
  { id: 'regular', name: 'Régulier', description: 'Quatre semaines consécutives portent ta trace.', condition: 'Effectuer au moins un call validé pendant 4 semaines consécutives.', category: 'calls', rarity: 'rare', visualFamily: 'segmented-mechanism', accent: '#7FC7E9', isSecret: false },
  { id: 'social_bond', name: 'Lien social', description: 'Une mission collective a atteint son objectif avec toi.', condition: 'Participer à une mission collective menée jusqu’à 100 %.', category: 'social', rarity: 'rare', visualFamily: 'linked-nodes-amber', accent: '#FFB84D', isSecret: false },
  { id: 'rally', name: 'Ralliement', description: 'Dix nouveaux signaux ont rejoint les couleurs de ta faction.', condition: 'Faire gagner 10 supporters à sa faction.', category: 'faction', rarity: 'epic', visualFamily: 'linked-nodes-volt', accent: '#E8FF3D', isSecret: false },
  { id: 'standard_bearer', name: 'Porte-étendard', description: 'Dix victoires collectives portent ton empreinte.', condition: 'Contribuer à 10 missions collectives victorieuses.', category: 'faction', rarity: 'epic', visualFamily: 'standard-bronze', accent: '#D3904F', isSecret: false },
  { id: 'faction_loyal', name: 'Fidèle à la faction', description: 'Chaque semaine de la saison porte la même couleur.', condition: 'Contribuer à sa faction chaque semaine pendant une saison complète.', category: 'faction', rarity: 'epic', visualFamily: 'reinforced-bronze', accent: '#B97842', isSecret: false },
  { id: 'season_elite', name: 'Élite de saison', description: 'Une saison officiellement close parmi les dix meilleurs pour cent.', condition: 'Terminer une saison dans le top 10 % après sa clôture officielle.', category: 'season', rarity: 'epic', visualFamily: 'crystal-hourglass', accent: '#9A6BFF', isSecret: false },
  { id: 'griff_legend', name: 'Légende GRIFF', description: 'Une saison inscrite dans le percentile le plus rare.', condition: 'Terminer une saison dans le top 1 % après sa clôture officielle.', category: 'season', rarity: 'legendary', visualFamily: 'legend-medallion', accent: '#E5C07B', isSecret: false },
  { id: 'perfect_eclipse', name: 'Éclipse parfaite', description: 'Les cinq décisions du placement n’ont laissé aucune ombre.', condition: 'Réussir les 5 verdicts de placement.', category: 'secret', rarity: 'secret', visualFamily: 'revealed-eclipse', sealedVisualFamily: 'sealed-eclipse', accent: '#31D7E2', isSecret: true, clue: 'Cinq décisions. Aucune ombre.' },
  { id: 'countercurrent', name: 'Contre-courant', description: 'Tu as lu juste quand presque tous les autres regardaient ailleurs.', condition: 'Réussir un call choisi par 10 % des participants ou moins.', category: 'secret', rarity: 'secret', visualFamily: 'revealed-countercurrent', sealedVisualFamily: 'sealed-countercurrent', accent: '#E8FF3D', isSecret: true, clue: 'La foule regardait ailleurs.' },
  { id: 'resurgence', name: 'Résurgence', description: 'Une série neuve s’est élevée depuis trois chutes consécutives.', condition: 'Après 3 calls incorrects consécutifs, réussir 5 calls consécutifs.', category: 'secret', rarity: 'secret', visualFamily: 'revealed-resurgence', sealedVisualFamily: 'sealed-resurgence', accent: '#FF9C42', isSecret: true, clue: 'La chute n’était pas la fin.' },
  { id: 'synchrony', name: 'Synchronie', description: 'Deux trajectoires ont produit trois verdicts identiques et justes.', condition: 'Réussir avec un ami les mêmes 3 calls consécutifs.', category: 'secret', rarity: 'secret', visualFamily: 'revealed-synchrony', sealedVisualFamily: 'sealed-synchrony', accent: '#6F7DFF', isSecret: true, clue: 'Deux signaux, une trajectoire.' },
  { id: 'zero_chronicle', name: 'Chronique Zéro', description: 'Aucune semaine de la saison complète ne manque au registre.', condition: 'Effectuer au moins un call validé chaque semaine d’une saison complète.', category: 'secret', rarity: 'secret', visualFamily: 'revealed-chronicle', sealedVisualFamily: 'sealed-chronicle', accent: '#E8EEF3', isSecret: true, clue: 'Aucune semaine ne manque.' },
] as const;

export const ACHIEVEMENT_BADGE_BY_ID = new Map<BadgeId, AchievementBadgeDefinition>(
  ACHIEVEMENT_BADGE_CATALOG.map((badge) => [badge.id, badge]),
);
