export const TEAM_LOGOS: Record<string, string> = {
  Astralis: 'https://commons.wikimedia.org/wiki/Special:FilePath/Astralis_logo.svg',
  DRX: 'https://commons.wikimedia.org/wiki/Special:FilePath/DRX_logo_2023.png',
  'EDward Gaming': 'https://commons.wikimedia.org/wiki/Special:FilePath/Edward_Gaming_logo.png',
  'FaZe Clan': 'https://commons.wikimedia.org/wiki/Special:FilePath/FaZe_Clan_2025_svg.svg',
  Fnatic: 'https://cdn.sanity.io/images/5gii1snx/production/22ded60518ddaf71975d334849039189cb106e87-1000x1000.png',
  'G2 Esports': 'https://static.cdnlogo.com/logos/g/28/g2.svg',
  GiantX: 'https://giantx.gg/cdn/shop/files/logo_0620238f-1e58-435d-bcd2-aa131bba7992_600x.png?v=1772036626',
  Heroic: 'https://commons.wikimedia.org/wiki/Special:FilePath/Heroic_2023_logo.png',
  'Karmine Corp': 'https://commons.wikimedia.org/wiki/Special:FilePath/Karmine_Corp_logo.svg',
  MOUZ: 'https://commons.wikimedia.org/wiki/Special:FilePath/MOUZlogo2021.png',
  'Movistar KOI': 'https://commons.wikimedia.org/wiki/Special:FilePath/Movistar_KOI_Logo.webp',
  NAVI: 'https://commons.wikimedia.org/wiki/Special:FilePath/Navilogo.jpg',
  'Natus Vincere': 'https://commons.wikimedia.org/wiki/Special:FilePath/Navilogo.jpg',
  'Paper Rex': 'https://commons.wikimedia.org/wiki/Special:FilePath/Paper_Rex_logo.svg',
  Rogue: 'https://www.google.com/s2/favicons?domain=rogue.gg&sz=256',
  'SK Gaming': 'https://commons.wikimedia.org/wiki/Special:FilePath/SK_Gaming_Logo_2022.svg',
  Sentinels: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sentinels_logo.svg',
  T1: 'https://commons.wikimedia.org/wiki/Special:FilePath/T1_esports_logo.svg',
  'Team BDS': 'https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/9e/Team_BDSlogo_square.png',
  'Team Falcons': 'https://www.google.com/s2/favicons?domain=falcons.sa&sz=256',
  'Team Heretics': 'https://teamheretics.com/en/modules/wim_esports/views/img/heretics-logo-png.webp',
  'Team Liquid': 'https://commons.wikimedia.org/wiki/Special:FilePath/Team_Liquid_logo.svg',
  'Team Spirit': 'https://commons.wikimedia.org/wiki/Special:FilePath/Team_Spirit_new_em.svg',
  'Team Vitality': 'https://static.cdnlogo.com/logos/t/89/team-vitality.svg',
  'Virtus.pro': 'https://www.google.com/s2/favicons?domain=virtus.pro&sz=256',
};
